const questoesMédio = [
    {
    "subsistema": "Médio",
    "fase": "F",
    "tema": "Potenciação",
    "pergunta": "Quanto é 2⁴?",
    "A": "6",
    "B": "8",
    "C": "16",
    "D": "10",
    "resposta": "C"
  },
  {
    "subsistema": "Médio",
    "fase": "F",
    "tema": "Radiciação",
    "pergunta": "Quanto é a raiz quadrada de 36?",
    "A": "5",
    "B": "6",
    "C": "4",
    "D": "7",
    "resposta": "B"
  },
  {
    "subsistema": "Médio",
    "fase": "F",
    "tema": "Operações com frações",
    "pergunta": "Quanto é 1/2 + 1/4?",
    "A": "3/4",
    "B": "2/6",
    "C": "1/8",
    "D": "1/3",
    "resposta": "A"
  },
  {
    "subsistema": "Médio",
    "fase": "F",
    "tema": "Expressões algébricas",
    "pergunta": "Simplifique: 2x + 3x",
    "A": "6x",
    "B": "5x",
    "C": "4x",
    "D": "x",
    "resposta": "B"
  },
  {
    "subsistema": "Médio",
    "fase": "F",
    "tema": "Produtos notáveis",
    "pergunta": "Qual o resultado de (a + b)²?",
    "A": "a² + b²",
    "B": "a² + 2ab + b²",
    "C": "a² - 2ab + b²",
    "D": "a² - b²",
    "resposta": "B"
  },
  {
    "subsistema": "Médio",
    "fase": "F",
    "tema": "Fatoração",
    "pergunta": "Fatore: x² + 5x + 6",
    "A": "(x + 3)(x + 2)",
    "B": "(x + 2)(x - 3)",
    "C": "(x - 2)(x - 3)",
    "D": "(x + 1)(x + 6)",
    "resposta": "A"
  },
  {
    "subsistema": "Médio",
    "fase": "F",
    "tema": "Equação do 1º grau",
    "pergunta": "Resolva: 3x - 6 = 0",
    "A": "x = 3",
    "B": "x = -2",
    "C": "x = 6",
    "D": "x = 2",
    "resposta": "A"
  },
  {
    "subsistema": "Médio",
    "fase": "F",
    "tema": "Equação do 2º grau",
    "pergunta": "Resolva: x² - 4 = 0",
    "A": "x = ±2",
    "B": "x = ±4",
    "C": "x = ±1",
    "D": "x = ±3",
    "resposta": "A"
  },
  {
    "subsistema": "Médio",
    "fase": "F",
    "tema": "Sistema de equações",
    "pergunta": "Resolva o sistema: x + y = 5 e x - y = 1",
    "A": "x=3, y=2",
    "B": "x=4, y=1",
    "C": "x=5, y=0",
    "D": "x=2, y=3",
    "resposta": "A"
  },
  {
    "subsistema": "Médio",
    "fase": "F",
    "tema": "Módulo",
    "pergunta": "Qual é o valor de |−7|?",
    "A": "-7",
    "B": "7",
    "C": "0",
    "D": "−14",
    "resposta": "B"
  },
  {
    "subsistema": "Médio",
    "fase": "F",
    "tema": "Razões e proporções",
    "pergunta": "Qual é a razão entre 10 e 2?",
    "A": "5",
    "B": "2",
    "C": "8",
    "D": "12",
    "resposta": "A"
  },
  {
    "subsistema": "Médio",
    "fase": "F",
    "tema": "Porcentagem",
    "pergunta": "Quanto é 25% de 200?",
    "A": "100",
    "B": "75",
    "C": "50",
    "D": "25",
    "resposta": "C"
  },
  {
    "subsistema": "Médio",
    "fase": "F",
    "tema": "Unidades de medida",
    "pergunta": "Quantos metros há em 3,5 km?",
    "A": "3500",
    "B": "3000",
    "C": "350",
    "D": "35",
    "resposta": "A"
  },
  {
    "subsistema": "Médio",
    "fase": "F",
    "tema": "Volume",
    "pergunta": "Qual é o volume de um cubo de lado 2 cm?",
    "A": "4 cm³",
    "B": "8 cm³",
    "C": "6 cm³",
    "D": "10 cm³",
    "resposta": "B"
  },
  {
    "subsistema": "Médio",
    "fase": "F",
    "tema": "Área do quadrado",
    "pergunta": "Qual é a área de um quadrado com lado 5 cm?",
    "A": "25 cm²",
    "B": "20 cm²",
    "C": "10 cm²",
    "D": "15 cm²",
    "resposta": "A"
  },
  {
    "subsistema": "Médio",
    "fase": "F",
    "tema": "Área do triângulo",
    "pergunta": "Um triângulo tem base 6 cm e altura 4 cm. Qual é a sua área?",
    "A": "24 cm²",
    "B": "10 cm²",
    "C": "12 cm²",
    "D": "15 cm²",
    "resposta": "C"
  },
  {
    "subsistema": "Médio",
    "fase": "F",
    "tema": "Divisão",
    "pergunta": "Quanto é 144 ÷ 12?",
    "A": "12",
    "B": "11",
    "C": "10",
    "D": "13",
    "resposta": "A"
  },
  {
    "subsistema": "Médio",
    "fase": "F",
    "tema": "Multiplicação",
    "pergunta": "Quanto é 15 × 4?",
    "A": "60",
    "B": "45",
    "C": "55",
    "D": "50",
    "resposta": "A"
  },
  {
    "subsistema": "Médio",
    "fase": "F",
    "tema": "Expressões numéricas",
    "pergunta": "Resolva: 5 + 3 × 2",
    "A": "11",
    "B": "16",
    "C": "13",
    "D": "10",
    "resposta": "A"
  },
  {
    "subsistema": "Médio",
    "fase": "F",
    "tema": "Múltiplos e divisores",
    "pergunta": "Qual é o menor múltiplo comum entre 4 e 6?",
    "A": "12",
    "B": "24",
    "C": "6",
    "D": "18",
    "resposta": "A"
  },
  {
    "subsistema": "Médio",
    "fase": "F",
    "tema": "Potenciação",
    "pergunta": "Quanto é 5²?",
    "A": "10",
    "B": "20",
    "C": "25",
    "D": "15",
    "resposta": "C"
  },
  {
    "subsistema": "Médio",
    "fase": "F",
    "tema": "Radiciação",
    "pergunta": "Qual é a raiz quadrada de 64?",
    "A": "6",
    "B": "7",
    "C": "8",
    "D": "9",
    "resposta": "C"
  },
  {
    "subsistema": "Médio",
    "fase": "F",
    "tema": "Equações",
    "pergunta": "Resolva: 2x + 4 = 10",
    "A": "x = 2",
    "B": "x = 3",
    "C": "x = 4",
    "D": "x = 1",
    "resposta": "B"
  },
  {
    "subsistema": "Médio",
    "fase": "F",
    "tema": "Funções",
    "pergunta": "Se f(x) = 2x, quanto é f(5)?",
    "A": "7",
    "B": "10",
    "C": "15",
    "D": "5",
    "resposta": "B"
  },
  {
    "subsistema": "Médio",
    "fase": "F",
    "tema": "Álgebra",
    "pergunta": "Simplifique: 3x + 5x",
    "A": "15x",
    "B": "8x",
    "C": "10x",
    "D": "5x",
    "resposta": "B"
  },
  {
    "subsistema": "Médio",
    "fase": "F",
    "tema": "Geometria",
    "pergunta": "Qual é a área de um quadrado de lado 4 cm?",
    "A": "8 cm²",
    "B": "12 cm²",
    "C": "16 cm²",
    "D": "10 cm²",
    "resposta": "C"
  },
  {
    "subsistema": "Médio",
    "fase": "F",
    "tema": "Trigonometria",
    "pergunta": "Qual o seno de 30°?",
    "A": "0,5",
    "B": "1",
    "C": "√3/2",
    "D": "0",
    "resposta": "A"
  },
  {
    "subsistema": "Médio",
    "fase": "F",
    "tema": "Estatística",
    "pergunta": "Qual é a média de 2, 4, 6, 8?",
    "A": "4",
    "B": "5",
    "C": "6",
    "D": "7",
    "resposta": "B"
  },
  {
    "subsistema": "Médio",
    "fase": "F",
    "tema": "Porcentagem",
    "pergunta": "Quanto é 10% de 200?",
    "A": "10",
    "B": "15",
    "C": "20",
    "D": "25",
    "resposta": "C"
  },
  {
    "subsistema": "Médio",
    "fase": "F",
    "tema": "Sistema de equações",
    "pergunta": "Resolva o sistema: x + y = 6 e x - y = 2",
    "A": "x = 4, y = 2",
    "B": "x = 3, y = 3",
    "C": "x = 5, y = 1",
    "D": "x = 2, y = 4",
    "resposta": "A"
  },
  {
    "subsistema": "Médio",
    "fase": "F",
    "tema": "Potenciação",
    "pergunta": "Quanto é 4³?",
    "A": "64",
    "B": "16",
    "C": "12",
    "D": "8",
    "resposta": "A"
  },
  {
    "subsistema": "Médio",
    "fase": "F",
    "tema": "Radiciação",
    "pergunta": "Qual é a raiz cúbica de 27?",
    "A": "2",
    "B": "3",
    "C": "9",
    "D": "6",
    "resposta": "B"
  },
  {
    "subsistema": "Médio",
    "fase": "F",
    "tema": "Equações",
    "pergunta": "Resolva: x/2 + 3 = 7",
    "A": "x = 6",
    "B": "x = 8",
    "C": "x = 4",
    "D": "x = 2",
    "resposta": "A"
  },
  {
    "subsistema": "Médio",
    "fase": "F",
    "tema": "Funções",
    "pergunta": "Se f(x) = x², quanto é f(3)?",
    "A": "3",
    "B": "6",
    "C": "9",
    "D": "12",
    "resposta": "C"
  },
  {
    "subsistema": "Médio",
    "fase": "F",
    "tema": "Álgebra",
    "pergunta": "Resolva: (x + 2)(x + 3) = ?",
    "A": "x² + 6x + 5",
    "B": "x² + 5x + 6",
    "C": "x² + 4x + 6",
    "D": "x² + 3x + 2",
    "resposta": "B"
  },
  {
    "subsistema": "Médio",
    "fase": "F",
    "tema": "Geometria",
    "pergunta": "Qual é o perímetro de um triângulo com lados 3 cm, 4 cm e 5 cm?",
    "A": "12 cm",
    "B": "10 cm",
    "C": "15 cm",
    "D": "9 cm",
    "resposta": "A"
  },
  {
    "subsistema": "Médio",
    "fase": "F",
    "tema": "Trigonometria",
    "pergunta": "Qual o cosseno de 60°?",
    "A": "0,5",
    "B": "1",
    "C": "√3/2",
    "D": "0",
    "resposta": "A"
  },
  {
    "subsistema": "Médio",
    "fase": "F",
    "tema": "Estatística",
    "pergunta": "Qual é a mediana da sequência: 3, 5, 7, 9, 11?",
    "A": "5",
    "B": "7",
    "C": "9",
    "D": "8",
    "resposta": "B"
  },
  {
    "subsistema": "Médio",
    "fase": "F",
    "tema": "Porcentagem",
    "pergunta": "Quanto é 15% de 80?",
    "A": "12",
    "B": "14",
    "C": "10",
    "D": "16",
    "resposta": "A"
  },
  {
    "subsistema": "Médio",
    "fase": "F",
    "tema": "Sistema de equações",
    "pergunta": "Resolva o sistema: x + 2y = 10 e x - y = 1",
    "A": "x=4, y=3",
    "B": "x=5, y=2",
    "C": "x=6, y=2",
    "D": "x=7, y=1",
    "resposta": "B"
  },
  {
    "subsistema": "Médio",
    "fase": "F",
    "tema": "Potenciação",
    "pergunta": "Quanto é 4³?",
    "A": "64",
    "B": "16",
    "C": "12",
    "D": "8",
    "resposta": "A"
  },
  {
    "subsistema": "Médio",
    "fase": "F",
    "tema": "Radiciação",
    "pergunta": "Qual é a raiz cúbica de 27?",
    "A": "2",
    "B": "3",
    "C": "9",
    "D": "6",
    "resposta": "B"
  },
  {
    "subsistema": "Médio",
    "fase": "F",
    "tema": "Equações",
    "pergunta": "Resolva: x/2 + 3 = 7",
    "A": "x = 6",
    "B": "x = 8",
    "C": "x = 4",
    "D": "x = 2",
    "resposta": "A"
  },
  {
    "subsistema": "Médio",
    "fase": "F",
    "tema": "Funções",
    "pergunta": "Se f(x) = x², quanto é f(3)?",
    "A": "3",
    "B": "6",
    "C": "9",
    "D": "12",
    "resposta": "C"
  },
  {
    "subsistema": "Médio",
    "fase": "F",
    "tema": "Álgebra",
    "pergunta": "Resolva: (x + 2)(x + 3) = ?",
    "A": "x² + 6x + 5",
    "B": "x² + 5x + 6",
    "C": "x² + 4x + 6",
    "D": "x² + 3x + 2",
    "resposta": "B"
  },
  {
    "subsistema": "Médio",
    "fase": "F",
    "tema": "Geometria",
    "pergunta": "Qual é o perímetro de um triângulo com lados 3 cm, 4 cm e 5 cm?",
    "A": "12 cm",
    "B": "10 cm",
    "C": "15 cm",
    "D": "9 cm",
    "resposta": "A"
  },
  {
    "subsistema": "Médio",
    "fase": "F",
    "tema": "Trigonometria",
    "pergunta": "Qual o cosseno de 60°?",
    "A": "0,5",
    "B": "1",
    "C": "√3/2",
    "D": "0",
    "resposta": "A"
  },
  {
    "subsistema": "Médio",
    "fase": "F",
    "tema": "Estatística",
    "pergunta": "Qual é a mediana da sequência: 3, 5, 7, 9, 11?",
    "A": "5",
    "B": "7",
    "C": "9",
    "D": "8",
    "resposta": "B"
  },
  {
    "subsistema": "Médio",
    "fase": "F",
    "tema": "Porcentagem",
    "pergunta": "Quanto é 15% de 80?",
    "A": "12",
    "B": "14",
    "C": "10",
    "D": "16",
    "resposta": "A"
  },
  {
    "subsistema": "Médio",
    "fase": "F",
    "tema": "Sistema de equações",
    "pergunta": "Resolva o sistema: x + 2y = 10 e x - y = 1",
    "A": "x=4, y=3",
    "B": "x=5, y=2",
    "C": "x=6, y=2",
    "D": "x=7, y=1",
    "resposta": "B"
  },
  {
    "subsistema": "Médio",
    "fase": "F",
    "tema": "Potenciação",
    "pergunta": "Quanto é 3 elevado à 3ª potência?",
    "A": "6",
    "B": "9",
    "C": "27",
    "D": "81",
    "resposta": "C"
  },
  {
    "subsistema": "Médio",
    "fase": "F",
    "tema": "Radiciação",
    "pergunta": "Qual é a raiz quadrada de 49?",
    "A": "5",
    "B": "6",
    "C": "7",
    "D": "8",
    "resposta": "C"
  },
  {
    "subsistema": "Médio",
    "fase": "F",
    "tema": "Equações",
    "pergunta": "Resolva: 4x - 8 = 0",
    "A": "x = 2",
    "B": "x = 4",
    "C": "x = 6",
    "D": "x = 8",
    "resposta": "A"
  },
  {
    "subsistema": "Médio",
    "fase": "F",
    "tema": "Funções",
    "pergunta": "Se f(x) = x + 7, quanto é f(3)?",
    "A": "10",
    "B": "7",
    "C": "6",
    "D": "9",
    "resposta": "A"
  },
  {
    "subsistema": "Médio",
    "fase": "F",
    "tema": "Álgebra",
    "pergunta": "Simplifique: 5x - 2x + x",
    "A": "6x",
    "B": "4x",
    "C": "5x",
    "D": "3x",
    "resposta": "A"
  },
  {
    "subsistema": "Médio",
    "fase": "F",
    "tema": "Geometria",
    "pergunta": "Quantos graus tem um triângulo?",
    "A": "90°",
    "B": "180°",
    "C": "360°",
    "D": "270°",
    "resposta": "B"
  },
  {
    "subsistema": "Médio",
    "fase": "F",
    "tema": "Trigonometria",
    "pergunta": "O seno de 90° é igual a:",
    "A": "0",
    "B": "0,5",
    "C": "1",
    "D": "√2/2",
    "resposta": "C"
  },
  {
    "subsistema": "Médio",
    "fase": "F",
    "tema": "Estatística",
    "pergunta": "Qual a média de 4, 6 e 10?",
    "A": "6",
    "B": "7",
    "C": "8",
    "D": "10",
    "resposta": "B"
  },
  {
    "subsistema": "Médio",
    "fase": "F",
    "tema": "Porcentagem",
    "pergunta": "Quanto é 25% de 200?",
    "A": "50",
    "B": "25",
    "C": "40",
    "D": "75",
    "resposta": "A"
  },
  {
    "subsistema": "Médio",
    "fase": "F",
    "tema": "Sistema de equações",
    "pergunta": "Resolva: x + y = 12 e x - y = 4",
    "A": "x = 8, y = 4",
    "B": "x = 6, y = 6",
    "C": "x = 10, y = 2",
    "D": "x = 7, y = 5",
    "resposta": "A"
  },
  {
    "subsistema": "Médio",
    "fase": "F",
    "tema": "Potenciação",
    "pergunta": "Quanto é 6²?",
    "A": "12",
    "B": "36",
    "C": "18",
    "D": "24",
    "resposta": "B"
  },
  {
    "subsistema": "Médio",
    "fase": "F",
    "tema": "Radiciação",
    "pergunta": "Qual é a raiz quadrada de 144?",
    "A": "11",
    "B": "13",
    "C": "12",
    "D": "10",
    "resposta": "C"
  },
  {
    "subsistema": "Médio",
    "fase": "F",
    "tema": "Equações",
    "pergunta": "Resolva: 5x = 25",
    "A": "x = 10",
    "B": "x = 2",
    "C": "x = 4",
    "D": "x = 5",
    "resposta": "D"
  },
  {
    "subsistema": "Médio",
    "fase": "F",
    "tema": "Funções",
    "pergunta": "Se f(x) = 2x + 1, qual é o valor de f(4)?",
    "A": "9",
    "B": "8",
    "C": "7",
    "D": "10",
    "resposta": "A"
  },
  {
    "subsistema": "Médio",
    "fase": "F",
    "tema": "Álgebra",
    "pergunta": "Resolva: (x + 1)(x + 2)",
    "A": "x² + 2x + 1",
    "B": "x² + 3x + 2",
    "C": "x² + x + 2",
    "D": "x² + 4x + 4",
    "resposta": "B"
  },
  {
    "subsistema": "Médio",
    "fase": "F",
    "tema": "Geometria",
    "pergunta": "Qual é a fórmula da área do triângulo?",
    "A": "base + altura",
    "B": "base × altura",
    "C": "base × altura ÷ 2",
    "D": "base² + altura²",
    "resposta": "C"
  },
  {
    "subsistema": "Médio",
    "fase": "F",
    "tema": "Trigonometria",
    "pergunta": "Qual o cosseno de 0°?",
    "A": "0",
    "B": "1",
    "C": "0,5",
    "D": "√3/2",
    "resposta": "B"
  },
  {
    "subsistema": "Médio",
    "fase": "F",
    "tema": "Estatística",
    "pergunta": "A média de 5, 10, 15 é:",
    "A": "10",
    "B": "9",
    "C": "8",
    "D": "12",
    "resposta": "A"
  },
  {
    "subsistema": "Médio",
    "fase": "F",
    "tema": "Porcentagem",
    "pergunta": "Se um artigo custa 120 Kz e sofre um desconto de 25%, qual é o valor final?",
    "A": "90 Kz",
    "B": "80 Kz",
    "C": "100 Kz",
    "D": "96 Kz",
    "resposta": "D"
  },
  {
    "subsistema": "Médio",
    "fase": "F",
    "tema": "Sistema de equações",
    "pergunta": "Resolva: 2x + y = 10 e x - y = 2",
    "A": "x = 4, y = 2",
    "B": "x = 3, y = 4",
    "C": "x = 5, y = 0",
    "D": "x = 2, y = 6",
    "resposta": "A"
  },
  {
    "subsistema": "Médio",
    "fase": "F",
    "tema": "Potenciação",
    "pergunta": "Quanto é 10²?",
    "A": "100",
    "B": "20",
    "C": "50",
    "D": "10",
    "resposta": "A"
  },
  {
    "subsistema": "Médio",
    "fase": "F",
    "tema": "Radiciação",
    "pergunta": "Qual é a raiz quadrada de 36?",
    "A": "5",
    "B": "6",
    "C": "7",
    "D": "8",
    "resposta": "B"
  },
  {
    "subsistema": "Médio",
    "fase": "F",
    "tema": "Equações",
    "pergunta": "Resolva: x - 7 = 5",
    "A": "x = 2",
    "B": "x = 12",
    "C": "x = 14",
    "D": "x = 6",
    "resposta": "B"
  },
  {
    "subsistema": "Médio",
    "fase": "F",
    "tema": "Funções",
    "pergunta": "Se f(x) = 5x, qual é f(2)?",
    "A": "10",
    "B": "7",
    "C": "5",
    "D": "15",
    "resposta": "A"
  },
  {
    "subsistema": "Médio",
    "fase": "F",
    "tema": "Álgebra",
    "pergunta": "Simplifique: 4x - 2x + 6x",
    "A": "8x",
    "B": "10x",
    "C": "12x",
    "D": "6x",
    "resposta": "B"
  },
  {
    "subsistema": "Médio",
    "fase": "F",
    "tema": "Geometria",
    "pergunta": "Qual é a soma dos ângulos internos de um quadrado?",
    "A": "180°",
    "B": "270°",
    "C": "360°",
    "D": "90°",
    "resposta": "C"
  },
  {
    "subsistema": "Médio",
    "fase": "F",
    "tema": "Trigonometria",
    "pergunta": "Qual o seno de 45°?",
    "A": "√2/2",
    "B": "0,5",
    "C": "1",
    "D": "0",
    "resposta": "A"
  },
  {
    "subsistema": "Médio",
    "fase": "F",
    "tema": "Estatística",
    "pergunta": "Qual é a mediana da sequência: 2, 4, 6, 8, 10?",
    "A": "6",
    "B": "5",
    "C": "7",
    "D": "4",
    "resposta": "A"
  },
  {
    "subsistema": "Médio",
    "fase": "F",
    "tema": "Porcentagem",
    "pergunta": "20% de 300 é:",
    "A": "30",
    "B": "50",
    "C": "60",
    "D": "70",
    "resposta": "C"
  },
  {
    "subsistema": "Médio",
    "fase": "F",
    "tema": "Sistema de equações",
    "pergunta": "Resolva: 3x + y = 12 e x - y = 2",
    "A": "x = 3, y = 3",
    "B": "x = 4, y = 0",
    "C": "x = 5, y = 2",
    "D": "x = 2, y = 6",
    "resposta": "C"
  },
  {
    "subsistema": "Médio",
    "fase": "F",
    "tema": "Potenciação",
    "pergunta": "Qual o valor de 7²?",
    "A": "49",
    "B": "14",
    "C": "21",
    "D": "35",
    "resposta": "A"
  },
  {
    "subsistema": "Médio",
    "fase": "F",
    "tema": "Radiciação",
    "pergunta": "Qual é a raiz cúbica de 64?",
    "A": "3",
    "B": "4",
    "C": "5",
    "D": "6",
    "resposta": "B"
  },
  {
    "subsistema": "Médio",
    "fase": "F",
    "tema": "Equações",
    "pergunta": "Resolva: x + 9 = 13",
    "A": "x = 3",
    "B": "x = 4",
    "C": "x = 5",
    "D": "x = 6",
    "resposta": "B"
  },
  {
    "subsistema": "Médio",
    "fase": "F",
    "tema": "Funções",
    "pergunta": "Se f(x) = x² - 1, quanto é f(5)?",
    "A": "24",
    "B": "26",
    "C": "25",
    "D": "23",
    "resposta": "A"
  },
  {
    "subsistema": "Médio",
    "fase": "F",
    "tema": "Álgebra",
    "pergunta": "Fatorize: x² - 9",
    "A": "(x - 3)(x + 3)",
    "B": "(x - 1)(x + 9)",
    "C": "(x - 2)(x + 4)",
    "D": "(x - 3)(x - 3)",
    "resposta": "A"
  },
  {
    "subsistema": "Médio",
    "fase": "F",
    "tema": "Geometria",
    "pergunta": "Quantos lados tem um dodecágono?",
    "A": "10",
    "B": "12",
    "C": "14",
    "D": "8",
    "resposta": "B"
  },
  {
    "subsistema": "Médio",
    "fase": "F",
    "tema": "Trigonometria",
    "pergunta": "O cosseno de 90° é:",
    "A": "0",
    "B": "1",
    "C": "0,5",
    "D": "√3/2",
    "resposta": "A"
  },
  {
    "subsistema": "Médio",
    "fase": "F",
    "tema": "Estatística",
    "pergunta": "Qual a moda da sequência: 5, 5, 6, 6, 6, 7?",
    "A": "5",
    "B": "6",
    "C": "7",
    "D": "8",
    "resposta": "B"
  },
  {
    "subsistema": "Médio",
    "fase": "F",
    "tema": "Porcentagem",
    "pergunta": "Quanto é 10% de 250?",
    "A": "25",
    "B": "20",
    "C": "30",
    "D": "15",
    "resposta": "A"
  },
  {
    "subsistema": "Médio",
    "fase": "F",
    "tema": "Sistema de equações",
    "pergunta": "Resolva: 2x - y = 4 e x + y = 6",
    "A": "x = 2, y = 4",
    "B": "x = 3, y = 3",
    "C": "x = 4, y = 2",
    "D": "x = 5, y = 1",
    "resposta": "B"
  },

  {
    "subsistema": "Médio",
    "fase": "F",
    "tema": "Potenciação",
    "pergunta": "Qual o valor de 5³?",
    "A": "25",
    "B": "15",
    "C": "125",
    "D": "75",
    "resposta": "C"
  },
  {
    "subsistema": "Médio",
    "fase": "F",
    "tema": "Radiciação",
    "pergunta": "A raiz quadrada de 81 é:",
    "A": "8",
    "B": "7",
    "C": "9",
    "D": "10",
    "resposta": "C"
  },
  {
    "subsistema": "Médio",
    "fase": "F",
    "tema": "Equações",
    "pergunta": "Resolva: x + 5 = 9",
    "A": "x = 5",
    "B": "x = 4",
    "C": "x = 3",
    "D": "x = 2",
    "resposta": "B"
  },
  {
    "subsistema": "Médio",
    "fase": "F",
    "tema": "Funções",
    "pergunta": "Se f(x) = 3x - 1, quanto é f(3)?",
    "A": "8",
    "B": "6",
    "C": "9",
    "D": "7",
    "resposta": "A"
  },
  {
    "subsistema": "Médio",
    "fase": "F",
    "tema": "Álgebra",
    "pergunta": "Resolva: x² = 16",
    "A": "x = 4 ou -4",
    "B": "x = 2 ou -2",
    "C": "x = 8",
    "D": "x = 3 ou -3",
    "resposta": "A"
  },
  {
    "subsistema": "Médio",
    "fase": "F",
    "tema": "Geometria",
    "pergunta": "Um ângulo reto tem quantos graus?",
    "A": "180°",
    "B": "45°",
    "C": "90°",
    "D": "60°",
    "resposta": "C"
  },
  {
    "subsistema": "Médio",
    "fase": "F",
    "tema": "Trigonometria",
    "pergunta": "Qual o seno de 30°?",
    "A": "1/2",
    "B": "√2/2",
    "C": "√3/2",
    "D": "0",
    "resposta": "A"
  },
  {
    "subsistema": "Médio",
    "fase": "F",
    "tema": "Estatística",
    "pergunta": "A média de 8, 10 e 12 é:",
    "A": "10",
    "B": "9",
    "C": "11",
    "D": "12",
    "resposta": "A"
  },
  {
    "subsistema": "Médio",
    "fase": "F",
    "tema": "Porcentagem",
    "pergunta": "Qual é 15% de 200?",
    "A": "25",
    "B": "30",
    "C": "35",
    "D": "40",
    "resposta": "B"
  },
  {
    "subsistema": "Médio",
    "fase": "F",
    "tema": "Sistema de equações",
    "pergunta": "Resolva: x + y = 8 e x - y = 2",
    "A": "x = 5, y = 3",
    "B": "x = 4, y = 4",
    "C": "x = 6, y = 2",
    "D": "x = 3, y = 5",
    "resposta": "A"
  },
  {
    "subsistema": "Médio",
    "fase": "F",
    "tema": "Potenciação",
    "pergunta": "Qual o valor de 2⁴?",
    "A": "8",
    "B": "16",
    "C": "32",
    "D": "12",
    "resposta": "B"
  },
  {
    "subsistema": "Médio",
    "fase": "F",
    "tema": "Radiciação",
    "pergunta": "Raiz quadrada de 121 é:",
    "A": "10",
    "B": "11",
    "C": "12",
    "D": "13",
    "resposta": "B"
  },
  {
    "subsistema": "Médio",
    "fase": "F",
    "tema": "Equações",
    "pergunta": "Resolva: 3x - 6 = 0",
    "A": "x = 2",
    "B": "x = 1",
    "C": "x = 3",
    "D": "x = -2",
    "resposta": "A"
  },
  {
    "subsistema": "Médio",
    "fase": "F",
    "tema": "Funções",
    "pergunta": "Se f(x) = x², quanto é f(6)?",
    "A": "36",
    "B": "12",
    "C": "18",
    "D": "24",
    "resposta": "A"
  },
  {
    "subsistema": "Médio",
    "fase": "F",
    "tema": "Álgebra",
    "pergunta": "Simplifique: 3x + 2x - x",
    "A": "4x",
    "B": "5x",
    "C": "6x",
    "D": "3x",
    "resposta": "A"
  },
  {
    "subsistema": "Médio",
    "fase": "F",
    "tema": "Geometria",
    "pergunta": "Quantos lados tem um hexágono?",
    "A": "5",
    "B": "6",
    "C": "7",
    "D": "8",
    "resposta": "B"
  },
  {
    "subsistema": "Médio",
    "fase": "F",
    "tema": "Trigonometria",
    "pergunta": "Cosseno de 60° é:",
    "A": "1/2",
    "B": "√2/2",
    "C": "√3/2",
    "D": "0",
    "resposta": "A"
  },
  {
    "subsistema": "Médio",
    "fase": "F",
    "tema": "Estatística",
    "pergunta": "A média de 3, 6 e 9 é:",
    "A": "6",
    "B": "5",
    "C": "7",
    "D": "8",
    "resposta": "A"
  },
  {
    "subsistema": "Médio",
    "fase": "F",
    "tema": "Porcentagem",
    "pergunta": "30% de 150 é:",
    "A": "45",
    "B": "30",
    "C": "35",
    "D": "60",
    "resposta": "A"
  },
  {
    "subsistema": "Médio",
    "fase": "F",
    "tema": "Sistema de equações",
    "pergunta": "Resolva: x + y = 10 e x - y = 4",
    "A": "x = 7, y = 3",
    "B": "x = 6, y = 4",
    "C": "x = 8, y = 2",
    "D": "x = 5, y = 5",
    "resposta": "A"
  },
  {
    "subsistema": "Médio",
    "fase": "F",
    "tema": "Potenciação",
    "pergunta": "Qual o valor de 3³?",
    "A": "6",
    "B": "9",
    "C": "27",
    "D": "12",
    "resposta": "C"
  },
  {
    "subsistema": "Médio",
    "fase": "F",
    "tema": "Radiciação",
    "pergunta": "Raiz quadrada de 25 é:",
    "A": "4",
    "B": "5",
    "C": "6",
    "D": "7",
    "resposta": "B"
  },
  {
    "subsistema": "Médio",
    "fase": "F",
    "tema": "Equações",
    "pergunta": "Resolva: 2x = 10",
    "A": "x = 2",
    "B": "x = 4",
    "C": "x = 5",
    "D": "x = 10",
    "resposta": "C"
  },
  {
    "subsistema": "Médio",
    "fase": "F",
    "tema": "Funções",
    "pergunta": "Se f(x) = 2x², quanto é f(3)?",
    "A": "18",
    "B": "6",
    "C": "12",
    "D": "9",
    "resposta": "A"
  },
  {
    "subsistema": "Médio",
    "fase": "F",
    "tema": "Álgebra",
    "pergunta": "Qual é o resultado de (x - 1)(x + 1)?",
    "A": "x² - 2",
    "B": "x² + 1",
    "C": "x² - 1",
    "D": "x² + 2x + 1",
    "resposta": "C"
  },
  {
    "subsistema": "Médio",
    "fase": "F",
    "tema": "Geometria",
    "pergunta": "Qual é a fórmula da área do círculo?",
    "A": "2πr",
    "B": "πr²",
    "C": "πd²",
    "D": "2πd",
    "resposta": "B"
  },
  {
    "subsistema": "Médio",
    "fase": "F",
    "tema": "Trigonometria",
    "pergunta": "Qual o seno de 0°?",
    "A": "0",
    "B": "1",
    "C": "0,5",
    "D": "√2/2",
    "resposta": "A"
  },
  {
    "subsistema": "Médio",
    "fase": "F",
    "tema": "Estatística",
    "pergunta": "Moda da sequência 2, 2, 3, 4, 5, 5, 5:",
    "A": "2",
    "B": "3",
    "C": "5",
    "D": "4",
    "resposta": "C"
  },
  {
    "subsistema": "Médio",
    "fase": "F",
    "tema": "Porcentagem",
    "pergunta": "Qual é 5% de 400?",
    "A": "15",
    "B": "20",
    "C": "25",
    "D": "30",
    "resposta": "B"
  },
  {
    "subsistema": "Médio",
    "fase": "F",
    "tema": "Sistema de equações",
    "pergunta": "Resolva: x + y = 14 e x - y = 6",
    "A": "x = 10, y = 4",
    "B": "x = 8, y = 6",
    "C": "x = 9, y = 5",
    "D": "x = 7, y = 7",
    "resposta": "A"
  },
  {
    "subsistema": "Médio",
    "fase": "F",
    "tema": "Potenciação",
    "pergunta": "Quanto é 6²?",
    "A": "36",
    "B": "12",
    "C": "18",
    "D": "24",
    "resposta": "A"
  },
  {
    "subsistema": "Médio",
    "fase": "F",
    "tema": "Radiciação",
    "pergunta": "Raiz quadrada de 144 é:",
    "A": "10",
    "B": "11",
    "C": "12",
    "D": "13",
    "resposta": "C"
  },
  {
    "subsistema": "Médio",
    "fase": "F",
    "tema": "Equações",
    "pergunta": "Resolva: x - 2 = 8",
    "A": "x = 6",
    "B": "x = 10",
    "C": "x = 8",
    "D": "x = 12",
    "resposta": "B"
  },
  {
    "subsistema": "Médio",
    "fase": "F",
    "tema": "Funções",
    "pergunta": "Se f(x) = x + 2, quanto é f(9)?",
    "A": "11",
    "B": "10",
    "C": "12",
    "D": "9",
    "resposta": "A"
  },
  {
    "subsistema": "Médio",
    "fase": "F",
    "tema": "Álgebra",
    "pergunta": "Simplifique: 2x + 4x - 3x",
    "A": "2x",
    "B": "3x",
    "C": "4x",
    "D": "5x",
    "resposta": "B"
  },
  {
    "subsistema": "Médio",
    "fase": "F",
    "tema": "Geometria",
    "pergunta": "Um triângulo equilátero tem todos os lados:",
    "A": "Desiguais",
    "B": "Maiores",
    "C": "Iguais",
    "D": "Menores",
    "resposta": "C"
  },
  {
    "subsistema": "Médio",
    "fase": "F",
    "tema": "Trigonometria",
    "pergunta": "O cosseno de 0° é:",
    "A": "0",
    "B": "1",
    "C": "0,5",
    "D": "√3/2",
    "resposta": "B"
  },
  {
    "subsistema": "Médio",
    "fase": "F",
    "tema": "Estatística",
    "pergunta": "Qual é a mediana de 3, 5, 7, 9, 11?",
    "A": "5",
    "B": "7",
    "C": "6",
    "D": "9",
    "resposta": "B"
  },
  {
    "subsistema": "Médio",
    "fase": "F",
    "tema": "Porcentagem",
    "pergunta": "50% de 500 é:",
    "A": "150",
    "B": "250",
    "C": "300",
    "D": "200",
    "resposta": "B"
  },
  {
    "subsistema": "Médio",
    "fase": "F",
    "tema": "Sistema de equações",
    "pergunta": "Resolva: 2x + y = 10 e x - y = 1",
    "A": "x = 3, y = 4",
    "B": "x = 2, y = 6",
    "C": "x = 4, y = 2",
    "D": "x = 5, y = 0",
    "resposta": "C"
  },
  {
    "subsistema": "Médio",
    "fase": "I",
    "tema": "Funções",
    "pergunta": "A função f(x) = 2x - 3 é crescente ou decrescente?",
    "A": "Crescente",
    "B": "Decrescente",
    "C": "Constante",
    "D": "Inversa",
    "resposta": "A"
  },
  {
    "subsistema": "Médio",
    "fase": "I",
    "tema": "Radiciação",
    "pergunta": "Simplifique: √(49x²)",
    "A": "7x",
    "B": "x√49",
    "C": "49x",
    "D": "x/7",
    "resposta": "A"
  },
  {
    "subsistema": "Médio",
    "fase": "I",
    "tema": "Álgebra",
    "pergunta": "Fatorando x² + 7x + 10, obtemos:",
    "A": "(x+5)(x+2)",
    "B": "(x+4)(x+3)",
    "C": "(x+6)(x+1)",
    "D": "(x+5)(x+3)",
    "resposta": "A"
  },
  {
    "subsistema": "Médio",
    "fase": "I",
    "tema": "Trigonometria",
    "pergunta": "Se sen(θ) = 0,5, então θ pode ser:",
    "A": "30°",
    "B": "45°",
    "C": "60°",
    "D": "90°",
    "resposta": "A"
  },
  {
    "subsistema": "Médio",
    "fase": "I",
    "tema": "Estatística",
    "pergunta": "A média aritmética de 6, 8, 10 e 12 é:",
    "A": "9",
    "B": "10",
    "C": "11",
    "D": "8",
    "resposta": "A"
  },
  {
    "subsistema": "Médio",
    "fase": "I",
    "tema": "Porcentagem",
    "pergunta": "Se um produto custa 80Kz com 25% de desconto, qual o novo valor?",
    "A": "60Kz",
    "B": "65Kz",
    "C": "70Kz",
    "D": "75Kz",
    "resposta": "C"
  },
  {
    "subsistema": "Médio",
    "fase": "I",
    "tema": "Sistema de equações",
    "pergunta": "Resolva: x + 2y = 10 e x - y = 1",
    "A": "x = 4, y = 3",
    "B": "x = 5, y = 2.5",
    "C": "x = 6, y = 2",
    "D": "x = 7, y = 1.5",
    "resposta": "C"
  },
  {
    "subsistema": "Médio",
    "fase": "I",
    "tema": "Geometria",
    "pergunta": "Qual a soma dos ângulos internos de um hexágono?",
    "A": "720°",
    "B": "540°",
    "C": "1080°",
    "D": "900°",
    "resposta": "A"
  },
  {
    "subsistema": "Médio",
    "fase": "I",
    "tema": "Funções",
    "pergunta": "Se f(x) = x² + 4x + 3, quanto vale f(-1)?",
    "A": "0",
    "B": "2",
    "C": "4",
    "D": "6",
    "resposta": "A"
  },
  {
    "subsistema": "Médio",
    "fase": "I",
    "tema": "Álgebra",
    "pergunta": "Resolva: (x+3)(x-2) = 0",
    "A": "x = -3 ou 2",
    "B": "x = 3 ou -2",
    "C": "x = -3 ou -2",
    "D": "x = 3 ou 2",
    "resposta": "A"
  },
  {
    "subsistema": "Médio",
    "fase": "I",
    "tema": "Funções",
    "pergunta": "Se f(x) = x² - 2x + 1, quanto vale f(2)?",
    "A": "1",
    "B": "0",
    "C": "3",
    "D": "2",
    "resposta": "B"
  },
  {
    "subsistema": "Médio",
    "fase": "I",
    "tema": "Radiciação",
    "pergunta": "Simplifique: √(36a²)",
    "A": "6a",
    "B": "6√a",
    "C": "a√36",
    "D": "12a",
    "resposta": "A"
  },
  {
    "subsistema": "Médio",
    "fase": "I",
    "tema": "Álgebra",
    "pergunta": "Fatorando x² - 9, obtemos:",
    "A": "(x - 3)(x + 3)",
    "B": "(x - 9)(x + 1)",
    "C": "(x - 1)(x + 9)",
    "D": "(x - 3)²",
    "resposta": "A"
  },
  {
    "subsistema": "Médio",
    "fase": "I",
    "tema": "Trigonometria",
    "pergunta": "Qual o valor do seno de 90°?",
    "A": "0",
    "B": "1",
    "C": "1/2",
    "D": "√2/2",
    "resposta": "B"
  },
  {
    "subsistema": "Médio",
    "fase": "I",
    "tema": "Estatística",
    "pergunta": "A mediana da sequência 5, 7, 9, 12, 15 é:",
    "A": "7",
    "B": "9",
    "C": "8",
    "D": "12",
    "resposta": "B"
  },
  {
    "subsistema": "Médio",
    "fase": "I",
    "tema": "Porcentagem",
    "pergunta": "40% de 250 é:",
    "A": "75",
    "B": "100",
    "C": "125",
    "D": "80",
    "resposta": "D"
  },
  {
    "subsistema": "Médio",
    "fase": "I",
    "tema": "Sistema de equações",
    "pergunta": "Resolva: x + 3y = 15 e x - y = 3",
    "A": "x = 6, y = 3",
    "B": "x = 9, y = 2",
    "C": "x = 7, y = 2",
    "D": "x = 5, y = 4",
    "resposta": "A"
  },
  {
    "subsistema": "Médio",
    "fase": "I",
    "tema": "Geometria",
    "pergunta": "A área de um triângulo com base 10cm e altura 6cm é:",
    "A": "60cm²",
    "B": "30cm²",
    "C": "20cm²",
    "D": "40cm²",
    "resposta": "B"
  },
  {
    "subsistema": "Médio",
    "fase": "I",
    "tema": "Funções",
    "pergunta": "Se f(x) = 3x + 2, encontre x tal que f(x) = 14",
    "A": "4",
    "B": "5",
    "C": "3",
    "D": "6",
    "resposta": "A"
  },
  {
    "subsistema": "Médio",
    "fase": "I",
    "tema": "Álgebra",
    "pergunta": "Qual é o valor de x na equação: x² - 4x = 0?",
    "A": "x = 4",
    "B": "x = 2",
    "C": "x = 0 ou 4",
    "D": "x = 0 ou 2",
    "resposta": "D"
  },
  {
    "subsistema": "Médio",
    "fase": "I",
    "tema": "Trigonometria",
    "pergunta": "Qual o valor de cos(60°)?",
    "A": "1/2",
    "B": "√3/2",
    "C": "0",
    "D": "1",
    "resposta": "A"
  },
  {
    "subsistema": "Médio",
    "fase": "I",
    "tema": "Funções",
    "pergunta": "Se f(x) = -x² + 2x, quanto é f(3)?",
    "A": "-3",
    "B": "-9",
    "C": "3",
    "D": "0",
    "resposta": "D"
  },
  {
    "subsistema": "Médio",
    "fase": "I",
    "tema": "Geometria",
    "pergunta": "A soma dos ângulos internos de um octógono é:",
    "A": "1080°",
    "B": "1260°",
    "C": "1440°",
    "D": "960°",
    "resposta": "C"
  },
  {
    "subsistema": "Médio",
    "fase": "I",
    "tema": "Porcentagem",
    "pergunta": "20% de 120 é igual a:",
    "A": "20",
    "B": "22",
    "C": "24",
    "D": "26",
    "resposta": "C"
  },
  {
    "subsistema": "Médio",
    "fase": "I",
    "tema": "Estatística",
    "pergunta": "Moda da sequência: 2, 4, 4, 4, 6, 8, 10:",
    "A": "2",
    "B": "4",
    "C": "6",
    "D": "8",
    "resposta": "B"
  },
  {
    "subsistema": "Médio",
    "fase": "I",
    "tema": "Álgebra",
    "pergunta": "Fatorando x² - x - 6, obtemos:",
    "A": "(x - 3)(x + 2)",
    "B": "(x - 2)(x + 3)",
    "C": "(x + 2)(x + 3)",
    "D": "(x - 3)(x - 2)",
    "resposta": "A"
  },
  {
    "subsistema": "Médio",
    "fase": "I",
    "tema": "Sistema de equações",
    "pergunta": "Resolva: x + y = 7 e x - y = 1",
    "A": "x = 4, y = 3",
    "B": "x = 5, y = 2",
    "C": "x = 6, y = 1",
    "D": "x = 3, y = 4",
    "resposta": "A"
  },
  {
    "subsistema": "Médio",
    "fase": "I",
    "tema": "Funções",
    "pergunta": "Se f(x) = 2x² - 4x + 1, quanto vale f(1)?",
    "A": "-1",
    "B": "0",
    "C": "1",
    "D": "2",
    "resposta": "A"
  },
  {
    "subsistema": "Médio",
    "fase": "I",
    "tema": "Radiciação",
    "pergunta": "Simplifique: √(81a²b²)",
    "A": "9ab",
    "B": "ab√81",
    "C": "81ab",
    "D": "9a²b²",
    "resposta": "A"
  },
  {
    "subsistema": "Médio",
    "fase": "I",
    "tema": "Trigonometria",
    "pergunta": "Seno de 30° é igual a:",
    "A": "0,5",
    "B": "√2/2",
    "C": "1",
    "D": "0",
    "resposta": "A"
  },

  {
    "subsistema": "Médio",
    "fase": "I",
    "tema": "Álgebra",
    "pergunta": "Resolva: (x + 1)(x - 4) = 0",
    "A": "x = -1 ou 4",
    "B": "x = 1 ou -4",
    "C": "x = -1 ou -4",
    "D": "x = 1 ou 4",
    "resposta": "A"
  },
  {
    "subsistema": "Médio",
    "fase": "I",
    "tema": "Funções",
    "pergunta": "Se f(x) = x² - 5x + 6, encontre f(2)",
    "A": "0",
    "B": "2",
    "C": "4",
    "D": "6",
    "resposta": "A"
  },
  {
    "subsistema": "Médio",
    "fase": "I",
    "tema": "Geometria",
    "pergunta": "Um ângulo externo de um triângulo mede 60°, e um dos ângulos internos adjacentes mede 40°. O outro ângulo interno é:",
    "A": "80°",
    "B": "100°",
    "C": "60°",
    "D": "90°",
    "resposta": "C"
  },
  {
    "subsistema": "Médio",
    "fase": "I",
    "tema": "Trigonometria",
    "pergunta": "Cos(90°) é igual a:",
    "A": "0",
    "B": "1",
    "C": "-1",
    "D": "0,5",
    "resposta": "A"
  },
  {
    "subsistema": "Médio",
    "fase": "I",
    "tema": "Sistema de equações",
    "pergunta": "Resolva: 2x + y = 8 e x - y = 1",
    "A": "x = 3, y = 2",
    "B": "x = 3, y = 1",
    "C": "x = 2, y = 4",
    "D": "x = 4, y = 0",
    "resposta": "A"
  },
  {
    "subsistema": "Médio",
    "fase": "I",
    "tema": "Porcentagem",
    "pergunta": "Um produto teve aumento de 25%. Se custava 80Kz, qual o novo preço?",
    "A": "90Kz",
    "B": "95Kz",
    "C": "100Kz",
    "D": "120Kz",
    "resposta": "C"
  },
  {
    "subsistema": "Médio",
    "fase": "I",
    "tema": "Estatística",
    "pergunta": "A média de 4, 6, 8, 10 e 12 é:",
    "A": "8",
    "B": "7",
    "C": "6",
    "D": "10",
    "resposta": "A"
  },
  {
    "subsistema": "Médio",
    "fase": "I",
    "tema": "Radiciação",
    "pergunta": "√(121x²) é igual a:",
    "A": "11x",
    "B": "121x",
    "C": "x√121",
    "D": "x/11",
    "resposta": "A"
  },
  {
    "subsistema": "Médio",
    "fase": "I",
    "tema": "Funções",
    "pergunta": "Se f(x) = 2x² - x, quanto é f(3)?",
    "A": "15",
    "B": "18",
    "C": "21",
    "D": "12",
    "resposta": "A"
  },
  {
    "subsistema": "Médio",
    "fase": "I",
    "tema": "Álgebra",
    "pergunta": "Qual é o valor de x na equação: x² + 5x + 6 = 0?",
    "A": "x = -2 ou -3",
    "B": "x = 2 ou 3",
    "C": "x = -1 ou -6",
    "D": "x = 1 ou 6",
    "resposta": "A"
  },
  {
    "subsistema": "Médio",
    "fase": "I",
    "tema": "Trigonometria",
    "pergunta": "Se sen(θ) = √3/2, então θ é igual a:",
    "A": "60°",
    "B": "45°",
    "C": "30°",
    "D": "90°",
    "resposta": "A"
  },
  {
    "subsistema": "Médio",
    "fase": "I",
    "tema": "Sistema de equações",
    "pergunta": "Resolva: x + y = 9 e x - y = 1",
    "A": "x = 5, y = 4",
    "B": "x = 4, y = 5",
    "C": "x = 6, y = 3",
    "D": "x = 3, y = 6",
    "resposta": "A"
  },
  {
    "subsistema": "Médio",
    "fase": "I",
    "tema": "Geometria",
    "pergunta": "Quantas diagonais tem um octógono?",
    "A": "20",
    "B": "24",
    "C": "28",
    "D": "30",
    "resposta": "C"
  },
  {
    "subsistema": "Médio",
    "fase": "I",
    "tema": "Funções",
    "pergunta": "Se f(x) = x² - 6x + 9, qual o valor mínimo de f(x)?",
    "A": "0",
    "B": "3",
    "C": "9",
    "D": "-9",
    "resposta": "A"
  },
  {
    "subsistema": "Médio",
    "fase": "I",
    "tema": "Porcentagem",
    "pergunta": "30% de 500 é:",
    "A": "100",
    "B": "150",
    "C": "200",
    "D": "250",
    "resposta": "B"
  },
  {
    "subsistema": "Médio",
    "fase": "I",
    "tema": "Álgebra",
    "pergunta": "Simplifique: (x + 3)²",
    "A": "x² + 6x + 9",
    "B": "x² + 3",
    "C": "x² + 9",
    "D": "x² + 3x + 9",
    "resposta": "A"
  },
  {
    "subsistema": "Médio",
    "fase": "I",
    "tema": "Estatística",
    "pergunta": "A moda da sequência 2, 2, 3, 4, 5, 5, 5, 6 é:",
    "A": "2",
    "B": "5",
    "C": "3",
    "D": "4",
    "resposta": "B"
  },
  {
    "subsistema": "Médio",
    "fase": "I",
    "tema": "Radiciação",
    "pergunta": "Simplifique √(64x⁴)",
    "A": "8x²",
    "B": "64x²",
    "C": "8x",
    "D": "x²√64",
    "resposta": "A"
  },
  {
    "subsistema": "Médio",
    "fase": "I",
    "tema": "Funções",
    "pergunta": "Se f(x) = x² - 2x, então f(-1) =",
    "A": "3",
    "B": "1",
    "C": "0",
    "D": "-3",
    "resposta": "A"
  },
  {
    "subsistema": "Médio",
    "fase": "I",
    "tema": "Trigonometria",
    "pergunta": "Tangente de 45° é:",
    "A": "1",
    "B": "0",
    "C": "√3",
    "D": "1/√3",
    "resposta": "A"
  },
  {
    "subsistema": "Médio",
    "fase": "I",
    "tema": "Álgebra",
    "pergunta": "Resolva: (x - 2)(x - 3) = 0",
    "A": "x = 2 ou 3",
    "B": "x = -2 ou -3",
    "C": "x = 5",
    "D": "x = -5",
    "resposta": "A"
  },
  {
    "subsistema": "Médio",
    "fase": "I",
    "tema": "Sistema de equações",
    "pergunta": "Resolva: x + 2y = 10 e 2x - y = 4",
    "A": "x = 2, y = 4",
    "B": "x = 4, y = 3",
    "C": "x = 1, y = 5",
    "D": "x = 3, y = 2",
    "resposta": "A"
  },
  {
    "subsistema": "Médio",
    "fase": "I",
    "tema": "Funções",
    "pergunta": "Se f(x) = x² - 4x + 4, qual o valor mínimo de f(x)?",
    "A": "0",
    "B": "4",
    "C": "2",
    "D": "-4",
    "resposta": "A"
  },
  {
    "subsistema": "Médio",
    "fase": "I",
    "tema": "Geometria",
    "pergunta": "Quantos lados tem um decágono?",
    "A": "10",
    "B": "12",
    "C": "8",
    "D": "6",
    "resposta": "A"
  },
  {
    "subsistema": "Médio",
    "fase": "I",
    "tema": "Porcentagem",
    "pergunta": "Se um produto de 120Kz sofre um aumento de 10%, qual o novo valor?",
    "A": "132Kz",
    "B": "125Kz",
    "C": "138Kz",
    "D": "130Kz",
    "resposta": "A"
  },
  {
    "subsistema": "Médio",
    "fase": "I",
    "tema": "Radiciação",
    "pergunta": "Simplifique: √(100x²y²)",
    "A": "10xy",
    "B": "100xy",
    "C": "x√100y",
    "D": "10x²y",
    "resposta": "A"
  },
  {
    "subsistema": "Médio",
    "fase": "I",
    "tema": "Trigonometria",
    "pergunta": "Cos(30°) é igual a:",
    "A": "√3/2",
    "B": "1/2",
    "C": "0",
    "D": "1",
    "resposta": "A"
  },
  {
    "subsistema": "Médio",
    "fase": "I",
    "tema": "Estatística",
    "pergunta": "A mediana da sequência 3, 5, 7, 9, 11 é:",
    "A": "5",
    "B": "7",
    "C": "9",
    "D": "6",
    "resposta": "B"
  },
  {
    "subsistema": "Médio",
    "fase": "I",
    "tema": "Álgebra",
    "pergunta": "Fatorando x² - 16, obtemos:",
    "A": "(x - 4)(x + 4)",
    "B": "(x - 8)(x + 2)",
    "C": "(x - 2)(x + 8)",
    "D": "(x + 4)²",
    "resposta": "A"
  },
  {
    "subsistema": "Médio",
    "fase": "I",
    "tema": "Funções",
    "pergunta": "Se f(x) = 4x - x², quanto vale f(1)?",
    "A": "3",
    "B": "4",
    "C": "2",
    "D": "5",
    "resposta": "A"
  },
  {
    "subsistema": "Médio",
    "fase": "D",
    "tema": "Funções quadráticas",
    "pergunta": "Um projétil é lançado verticalmente, e sua altura (em metros) após t segundos é dada por h(t) = -5t² + 20t + 10. Qual a altura máxima atingida?",
    "A": "30 m",
    "B": "25 m",
    "C": "20 m",
    "D": "15 m",
    "resposta": "A"
  },
  {
    "subsistema": "Médio",
    "fase": "D",
    "tema": "Trigonometria",
    "pergunta": "Um triângulo tem dois lados medindo 7 cm e 10 cm, e o ângulo entre eles é de 60°. Qual é a área do triângulo?",
    "A": "35√3 cm²",
    "B": "70 cm²",
    "C": "35 cm²",
    "D": "17,5 cm²",
    "resposta": "A"
  },
  {
    "subsistema": "Médio",
    "fase": "D",
    "tema": "Estatística",
    "pergunta": "Em uma turma com 40 alunos, a média das notas foi 14. Se um novo aluno entrou na turma com nota 18, qual será a nova média?",
    "A": "14,1",
    "B": "14,5",
    "C": "14,4",
    "D": "14,2",
    "resposta": "D"
  },
  {
    "subsistema": "Médio",
    "fase": "D",
    "tema": "Sistema de equações",
    "pergunta": "Resolva o sistema: 3x + 2y = 16 e 2x - y = 1",
    "A": "x = 2, y = 5",
    "B": "x = 3, y = 2",
    "C": "x = 4, y = 2",
    "D": "x = 2, y = 3",
    "resposta": "D"
  },
  {
    "subsistema": "Médio",
    "fase": "D",
    "tema": "Geometria analítica",
    "pergunta": "Qual a distância entre os pontos A(2, 3) e B(7, 11)?",
    "A": "10",
    "B": "9",
    "C": "√89",
    "D": "√74",
    "resposta": "C"
  },
  {
    "subsistema": "Médio",
    "fase": "D",
    "tema": "Probabilidades",
    "pergunta": "Uma urna contém 5 bolas vermelhas, 3 azuis e 2 verdes. Qual a probabilidade de tirar uma bola azul ou verde?",
    "A": "0,5",
    "B": "0,7",
    "C": "0,4",
    "D": "0,6",
    "resposta": "A"
  },
  {
    "subsistema": "Médio",
    "fase": "D",
    "tema": "Logaritmos",
    "pergunta": "Qual o valor de x em log₂(x) = 5?",
    "A": "10",
    "B": "16",
    "C": "32",
    "D": "25",
    "resposta": "C"
  },
  {
    "subsistema": "Médio",
    "fase": "D",
    "tema": "Progressão aritmética",
    "pergunta": "O 10º termo de uma PA é 35 e o 1º termo é 5. Qual a razão?",
    "A": "3",
    "B": "4",
    "C": "5",
    "D": "6",
    "resposta": "C"
  },
  {
    "subsistema": "Médio",
    "fase": "D",
    "tema": "Função exponencial",
    "pergunta": "Se f(x) = 3ᵡ, quanto vale f(4)?",
    "A": "81",
    "B": "27",
    "C": "64",
    "D": "243",
    "resposta": "D"
  },
  {
    "subsistema": "Médio",
    "fase": "D",
    "tema": "Álgebra",
    "pergunta": "Resolva a inequação: x² - 9 < 0",
    "A": "x < -3 ou x > 3",
    "B": "-3 < x < 3",
    "C": "x > -3",
    "D": "x ≠ ±3",
    "resposta": "B"
  },
  {
    "subsistema": "Médio",
    "fase": "D",
    "tema": "Geometria analítica",
    "pergunta": "Qual a equação da reta que passa pelos pontos (1,2) e (3,6)?",
    "A": "y = 2x",
    "B": "y = x + 1",
    "C": "y = 4x - 2",
    "D": "y = 3x",
    "resposta": "A"
  },
  {
    "subsistema": "Médio",
    "fase": "D",
    "tema": "Probabilidade",
    "pergunta": "Em um baralho comum de 52 cartas, qual a probabilidade de sair uma carta de paus?",
    "A": "1/4",
    "B": "1/2",
    "C": "1/13",
    "D": "13/52",
    "resposta": "A"
  },
  {
    "subsistema": "Médio",
    "fase": "D",
    "tema": "Logaritmos",
    "pergunta": "Sabendo que log(10000) = 4, qual o valor de log(0,0001)?",
    "A": "-4",
    "B": "4",
    "C": "-2",
    "D": "-3",
    "resposta": "A"
  },
  {
    "subsistema": "Médio",
    "fase": "D",
    "tema": "Funções",
    "pergunta": "A função f(x) = x² - 6x + 9 representa uma parábola. Qual é seu vértice?",
    "A": "(3, 0)",
    "B": "(0, 9)",
    "C": "(6, -9)",
    "D": "(9, -6)",
    "resposta": "A"
  },
  {
    "subsistema": "Médio",
    "fase": "D",
    "tema": "Trigonometria",
    "pergunta": "Em um triângulo retângulo, sen(θ) = 3/5. Qual o valor de cos(θ)?",
    "A": "4/5",
    "B": "3/4",
    "C": "4/5",
    "D": "5/3",
    "resposta": "C"
  },
  {
    "subsistema": "Médio",
    "fase": "D",
    "tema": "Equações",
    "pergunta": "Resolva: x² - 5x + 6 = 0",
    "A": "x = 2 ou 3",
    "B": "x = -2 ou -3",
    "C": "x = 1 ou 6",
    "D": "x = 3 ou 6",
    "resposta": "A"
  },
  {
    "subsistema": "Médio",
    "fase": "D",
    "tema": "Estatística",
    "pergunta": "Em uma pesquisa, 10 pessoas deram as notas: 10, 9, 8, 7, 6, 5, 4, 3, 2, 1. Qual a mediana?",
    "A": "5,5",
    "B": "6",
    "C": "5",
    "D": "6,5",
    "resposta": "A"
  },
  {
    "subsistema": "Médio",
    "fase": "D",
    "tema": "PA e PG",
    "pergunta": "Quantos termos tem a PA de primeiro termo 3, razão 2 e último termo 21?",
    "A": "9",
    "B": "10",
    "C": "11",
    "D": "12",
    "resposta": "A"
  },
  {
    "subsistema": "Médio",
    "fase": "D",
    "tema": "Função exponencial",
    "pergunta": "Se f(x) = 2^x, quanto vale f(5)?",
    "A": "32",
    "B": "16",
    "C": "64",
    "D": "128",
    "resposta": "A"
  },
  {
    "subsistema": "Médio",
    "fase": "D",
    "tema": "Análise combinatória",
    "pergunta": "Quantos anagramas diferentes podem ser formados com a palavra 'MAL'? (sem letras repetidas)",
    "A": "6",
    "B": "3",
    "C": "12",
    "D": "9",
    "resposta": "A"
  },
  {
    "subsistema": "Médio",
    "fase": "D",
    "tema": "Função quadrática",
    "pergunta": "A função f(x) = -x² + 6x - 8 atinge seu valor máximo em:",
    "A": "x = 3",
    "B": "x = -3",
    "C": "x = 2",
    "D": "x = 4",
    "resposta": "A"
  },
  {
    "subsistema": "Médio",
    "fase": "D",
    "tema": "Trigonometria",
    "pergunta": "Dado sen(x) = 0,5 e x ∈ [0°, 180°], então x é:",
    "A": "30° ou 150°",
    "B": "45° ou 135°",
    "C": "60° ou 120°",
    "D": "90°",
    "resposta": "A"
  },
  {
    "subsistema": "Médio",
    "fase": "D",
    "tema": "Estatística",
    "pergunta": "Se a média das idades de 5 alunos é 18 anos e um aluno de 20 entra no grupo, qual será a nova média?",
    "A": "18,3",
    "B": "18,5",
    "C": "19",
    "D": "17,8",
    "resposta": "A"
  },
  {
    "subsistema": "Médio",
    "fase": "D",
    "tema": "Geometria analítica",
    "pergunta": "A equação da reta que passa pelos pontos (2, 3) e (6, 7) é:",
    "A": "y = x + 1",
    "B": "y = x + 2",
    "C": "y = x + 3",
    "D": "y = 2x - 1",
    "resposta": "A"
  },
  {
    "subsistema": "Médio",
    "fase": "D",
    "tema": "Logaritmos",
    "pergunta": "Se log(x) = 2, então log(√x) é igual a:",
    "A": "1",
    "B": "2",
    "C": "0",
    "D": "4",
    "resposta": "A"
  },
  {
    "subsistema": "Médio",
    "fase": "D",
    "tema": "Probabilidade",
    "pergunta": "Uma caixa tem 5 bolas vermelhas e 7 azuis. Qual a probabilidade de tirar uma vermelha?",
    "A": "5/12",
    "B": "7/12",
    "C": "1/2",
    "D": "3/5",
    "resposta": "A"
  },
  {
    "subsistema": "Médio",
    "fase": "D",
    "tema": "Sistema de equações",
    "pergunta": "Resolva: 2x - 3y = 7 e x + y = 5",
    "A": "x = 4, y = 1",
    "B": "x = 2, y = 3",
    "C": "x = 3, y = 2",
    "D": "x = 1, y = 4",
    "resposta": "A"
  },
  {
    "subsistema": "Médio",
    "fase": "D",
    "tema": "PA",
    "pergunta": "O 8º termo de uma PA de razão 3 e primeiro termo 2 é:",
    "A": "23",
    "B": "24",
    "C": "26",
    "D": "27",
    "resposta": "A"
  },
  {
    "subsistema": "Médio",
    "fase": "D",
    "tema": "Análise combinatória",
    "pergunta": "Quantos anagramas diferentes podem ser formados com a palavra 'CASA'?",
    "A": "12",
    "B": "24",
    "C": "6",
    "D": "4",
    "resposta": "A"
  },
  {
    "subsistema": "Médio",
    "fase": "D",
    "tema": "Funções",
    "pergunta": "Se f(x) = 2x + 3 e g(x) = x², quanto vale f(g(2))?",
    "A": "11",
    "B": "10",
    "C": "7",
    "D": "13",
    "resposta": "D"
  },
  {
    "subsistema": "Médio",
    "fase": "D",
    "tema": "Função exponencial",
    "pergunta": "A função f(x) = 2^x cresce:",
    "A": "Exponencialmente",
    "B": "Linearmente",
    "C": "Logaritmicamente",
    "D": "Constante",
    "resposta": "A"
  },
  {
    "subsistema": "Médio",
    "fase": "D",
    "tema": "Trigonometria",
    "pergunta": "Qual o valor de sen²(x) + cos²(x)?",
    "A": "1",
    "B": "0",
    "C": "depende de x",
    "D": "2",
    "resposta": "A"
  },
  {
    "subsistema": "Médio",
    "fase": "D",
    "tema": "Estatística",
    "pergunta": "Em um conjunto com média 10 e 8 elementos, qual a soma dos valores?",
    "A": "80",
    "B": "18",
    "C": "88",
    "D": "800",
    "resposta": "A"
  },
  {
    "subsistema": "Médio",
    "fase": "D",
    "tema": "PA",
    "pergunta": "Quantos termos há entre 5 e 50 numa PA de razão 5?",
    "A": "9",
    "B": "10",
    "C": "8",
    "D": "11",
    "resposta": "A"
  },
  {
    "subsistema": "Médio",
    "fase": "D",
    "tema": "Sistema de equações",
    "pergunta": "Resolva: 4x + y = 10 e x - y = 2",
    "A": "x = 2, y = 2",
    "B": "x = 3, y = -2",
    "C": "x = 1, y = 4",
    "D": "x = 2, y = -2",
    "resposta": "B"
  },
  {
    "subsistema": "Médio",
    "fase": "D",
    "tema": "Geometria analítica",
    "pergunta": "Qual a equação da circunferência com centro na origem e raio 5?",
    "A": "x² + y² = 25",
    "B": "x² + y² = 10",
    "C": "x² - y² = 25",
    "D": "x² + y² = 5",
    "resposta": "A"
  },
  {
    "subsistema": "Médio",
    "fase": "D",
    "tema": "Probabilidade",
    "pergunta": "Qual a probabilidade de lançar um dado e obter número par?",
    "A": "1/2",
    "B": "2/3",
    "C": "1/3",
    "D": "3/6",
    "resposta": "A"
  },
  {
    "subsistema": "Médio",
    "fase": "D",
    "tema": "Logaritmos",
    "pergunta": "Qual o valor de log₃(81)?",
    "A": "4",
    "B": "3",
    "C": "2",
    "D": "5",
    "resposta": "A"
  },
  {
    "subsistema": "Médio",
    "fase": "D",
    "tema": "Funções",
    "pergunta": "Se f(x) = x² - 2x - 3, o valor de x para que f(x) = 0 é:",
    "A": "x = -1 ou 3",
    "B": "x = 1 ou -3",
    "C": "x = -1 ou -3",
    "D": "x = 2 ou 3",
    "resposta": "A"
  },
  {
    "subsistema": "Médio",
    "fase": "D",
    "tema": "Análise combinatória",
    "pergunta": "De quantas formas diferentes podemos formar uma senha de 3 dígitos com números de 1 a 5 sem repetir?",
    "A": "60",
    "B": "120",
    "C": "20",
    "D": "10",
    "resposta": "A"
  },
   {
    "subsistema": "Médio",
    "fase": "Final",
    "tema": "Desafio Final",
    "pergunta": "Um estudante resolve uma equação do 2º grau, calcula uma média ponderada e, por fim, aplica uma fórmula trigonométrica. Essa sequência de raciocínio pertence a qual área?",
    "A": "Matemática aplicada e integrada",
    "B": "Trigonometria",
    "C": "Álgebra",
    "D": "Estatística",
    "resposta": "A"
  }
];
