const questoesICiclo = [
{
    "subsistema": "I Ciclo",
    "fase": "F",
    "tema": "Potência",
    "pergunta": "Quanto é 4²?",
    "A": "16",
    "B": "8",
    "C": "12",
    "D": "24",
    "resposta": "A"
  },
  {
    "subsistema": "I Ciclo",
    "fase": "F",
    "tema": "Raiz quadrada",
    "pergunta": "Qual é a raiz quadrada de 25?",
    "A": "5",
    "B": "6",
    "C": "4",
    "D": "7",
    "resposta": "A"
  },
  {
    "subsistema": "I Ciclo",
    "fase": "F",
    "tema": "Expressões numéricas",
    "pergunta": "Resolva: (3 + 2) × 2",
    "A": "10",
    "B": "12",
    "C": "6",
    "D": "14",
    "resposta": "A"
  },
  {
    "subsistema": "I Ciclo",
    "fase": "F",
    "tema": "Frações",
    "pergunta": "Qual é o resultado de 1/2 + 1/2?",
    "A": "1",
    "B": "2",
    "C": "3",
    "D": "1/4",
    "resposta": "A"
  },
  {
    "subsistema": "I Ciclo",
    "fase": "F",
    "tema": "Potência",
    "pergunta": "Quanto é 3²?",
    "A": "9",
    "B": "6",
    "C": "8",
    "D": "12",
    "resposta": "A"
  },
  {
    "subsistema": "I Ciclo",
    "fase": "F",
    "tema": "Raiz quadrada",
    "pergunta": "Qual é a raiz quadrada de 36?",
    "A": "6",
    "B": "7",
    "C": "5",
    "D": "9",
    "resposta": "A"
  },
  {
    "subsistema": "I Ciclo",
    "fase": "F",
    "tema": "Expressões numéricas",
    "pergunta": "Resolva: (4 + 1) × 3",
    "A": "15",
    "B": "12",
    "C": "9",
    "D": "18",
    "resposta": "A"
  },
  {
    "subsistema": "I Ciclo",
    "fase": "F",
    "tema": "Frações",
    "pergunta": "Qual é o resultado de 1/3 + 1/3?",
    "A": "2/3",
    "B": "1",
    "C": "1/2",
    "D": "3/3",
    "resposta": "A"
  },
  {
    "subsistema": "I Ciclo",
    "fase": "F",
    "tema": "Potência",
    "pergunta": "Quanto é 2³?",
    "A": "8",
    "B": "6",
    "C": "9",
    "D": "4",
    "resposta": "A"
  },
  {
    "subsistema": "I Ciclo",
    "fase": "F",
    "tema": "Raiz quadrada",
    "pergunta": "Qual é a raiz quadrada de 49?",
    "A": "7",
    "B": "8",
    "C": "6",
    "D": "9",
    "resposta": "A"
  },
  {
    "subsistema": "I Ciclo",
    "fase": "F",
    "tema": "Potência",
    "pergunta": "Quanto é 7²?",
    "A": "49",
    "B": "14",
    "C": "21",
    "D": "42",
    "resposta": "A"
  },
  {
    "subsistema": "I Ciclo",
    "fase": "F",
    "tema": "Raiz quadrada",
    "pergunta": "Qual é a raiz quadrada de 121?",
    "A": "11",
    "B": "10",
    "C": "12",
    "D": "9",
    "resposta": "A"
  },
  {
    "subsistema": "I Ciclo",
    "fase": "F",
    "tema": "Expressões numéricas",
    "pergunta": "Resolva: (5 + 2) × 4",
    "A": "28",
    "B": "32",
    "C": "20",
    "D": "35",
    "resposta": "A"
  },
  {
    "subsistema": "I Ciclo",
    "fase": "F",
    "tema": "Frações",
    "pergunta": "Quanto é 1/4 + 1/4?",
    "A": "2/4",
    "B": "1/2",
    "C": "3/4",
    "D": "4/4",
    "resposta": "A"
  },
  {
    "subsistema": "I Ciclo",
    "fase": "F",
    "tema": "Potência",
    "pergunta": "Quanto é 8²?",
    "A": "64",
    "B": "16",
    "C": "56",
    "D": "72",
    "resposta": "A"
  },
  {
    "subsistema": "I Ciclo",
    "fase": "F",
    "tema": "Raiz quadrada",
    "pergunta": "Qual é a raiz quadrada de 144?",
    "A": "12",
    "B": "11",
    "C": "10",
    "D": "13",
    "resposta": "A"
  },
  {
    "subsistema": "I Ciclo",
    "fase": "F",
    "tema": "Expressões numéricas",
    "pergunta": "Resolva: (10 - 2) × 3",
    "A": "24",
    "B": "18",
    "C": "30",
    "D": "27",
    "resposta": "A"
  },
  {
    "subsistema": "I Ciclo",
    "fase": "F",
    "tema": "Frações",
    "pergunta": "Quanto é 1/3 + 1/6?",
    "A": "3/6",
    "B": "1/2",
    "C": "2/3",
    "D": "1/1",
    "resposta": "B"
  },
  {
    "subsistema": "I Ciclo",
    "fase": "F",
    "tema": "Potência",
    "pergunta": "Quanto é 9²?",
    "A": "81",
    "B": "72",
    "C": "63",
    "D": "90",
    "resposta": "A"
  },
  {
    "subsistema": "I Ciclo",
    "fase": "F",
    "tema": "Raiz quadrada",
    "pergunta": "Qual é a raiz quadrada de 169?",
    "A": "13",
    "B": "12",
    "C": "14",
    "D": "15",
    "resposta": "A"
  },
  {
    "subsistema": "I Ciclo",
    "fase": "F",
    "tema": "Potência",
    "pergunta": "Quanto é 10²?",
    "A": "100",
    "B": "20",
    "C": "10",
    "D": "110",
    "resposta": "A"
  },
  {
    "subsistema": "I Ciclo",
    "fase": "F",
    "tema": "Raiz quadrada",
    "pergunta": "Qual é a raiz quadrada de 196?",
    "A": "14",
    "B": "13",
    "C": "12",
    "D": "15",
    "resposta": "A"
  },
  {
    "subsistema": "I Ciclo",
    "fase": "F",
    "tema": "Expressões numéricas",
    "pergunta": "Resolva: (7 + 5) × 2",
    "A": "24",
    "B": "20",
    "C": "22",
    "D": "26",
    "resposta": "A"
  },
  {
    "subsistema": "I Ciclo",
    "fase": "F",
    "tema": "Frações",
    "pergunta": "Quanto é 1/8 + 1/8?",
    "A": "2/8",
    "B": "1/4",
    "C": "1/2",
    "D": "3/8",
    "resposta": "A"
  },
  {
    "subsistema": "I Ciclo",
    "fase": "F",
    "tema": "Potência",
    "pergunta": "Quanto é 11²?",
    "A": "121",
    "B": "111",
    "C": "101",
    "D": "131",
    "resposta": "A"
  },
  {
    "subsistema": "I Ciclo",
    "fase": "F",
    "tema": "Raiz quadrada",
    "pergunta": "Qual é a raiz quadrada de 225?",
    "A": "15",
    "B": "14",
    "C": "13",
    "D": "16",
    "resposta": "A"
  },
  {
    "subsistema": "I Ciclo",
    "fase": "F",
    "tema": "Expressões numéricas",
    "pergunta": "Resolva: (9 - 3) × 4",
    "A": "24",
    "B": "20",
    "C": "30",
    "D": "28",
    "resposta": "A"
  },
  {
    "subsistema": "I Ciclo",
    "fase": "F",
    "tema": "Frações",
    "pergunta": "Quanto é 1/10 + 1/10?",
    "A": "2/10",
    "B": "1/5",
    "C": "3/10",
    "D": "1/2",
    "resposta": "A"
  },
  {
    "subsistema": "I Ciclo",
    "fase": "F",
    "tema": "Potência",
    "pergunta": "Quanto é 12²?",
    "A": "144",
    "B": "124",
    "C": "132",
    "D": "156",
    "resposta": "A"
  },
  {
    "subsistema": "I Ciclo",
    "fase": "F",
    "tema": "Raiz quadrada",
    "pergunta": "Qual é a raiz quadrada de 256?",
    "A": "16",
    "B": "15",
    "C": "14",
    "D": "13",
    "resposta": "A"
  },
  {
    "subsistema": "I Ciclo",
    "fase": "F",
    "tema": "Potência",
    "pergunta": "Quanto é 13²?",
    "A": "169",
    "B": "156",
    "C": "144",
    "D": "121",
    "resposta": "A"
  },
  {
    "subsistema": "I Ciclo",
    "fase": "F",
    "tema": "Raiz quadrada",
    "pergunta": "Qual é a raiz quadrada de 289?",
    "A": "17",
    "B": "16",
    "C": "15",
    "D": "18",
    "resposta": "A"
  },
  {
    "subsistema": "I Ciclo",
    "fase": "F",
    "tema": "Expressões numéricas",
    "pergunta": "Resolva: (6 + 4) × 5",
    "A": "50",
    "B": "40",
    "C": "60",
    "D": "30",
    "resposta": "A"
  },
  {
    "subsistema": "I Ciclo",
    "fase": "F",
    "tema": "Frações",
    "pergunta": "Quanto é 1/2 + 1/4?",
    "A": "3/4",
    "B": "1",
    "C": "2/4",
    "D": "5/4",
    "resposta": "A"
  },
  {
    "subsistema": "I Ciclo",
    "fase": "F",
    "tema": "Potência",
    "pergunta": "Quanto é 14²?",
    "A": "196",
    "B": "184",
    "C": "176",
    "D": "205",
    "resposta": "A"
  },
  {
    "subsistema": "I Ciclo",
    "fase": "F",
    "tema": "Raiz quadrada",
    "pergunta": "Qual é a raiz quadrada de 324?",
    "A": "18",
    "B": "17",
    "C": "16",
    "D": "15",
    "resposta": "A"
  },
  {
    "subsistema": "I Ciclo",
    "fase": "F",
    "tema": "Expressões numéricas",
    "pergunta": "Resolva: (8 + 2) × 3",
    "A": "30",
    "B": "24",
    "C": "18",
    "D": "20",
    "resposta": "A"
  },
  {
    "subsistema": "I Ciclo",
    "fase": "F",
    "tema": "Frações",
    "pergunta": "Quanto é 1/3 + 1/3 + 1/3?",
    "A": "1",
    "B": "3/3",
    "C": "2/3",
    "D": "1/2",
    "resposta": "A"
  },
  {
    "subsistema": "I Ciclo",
    "fase": "F",
    "tema": "Potência",
    "pergunta": "Quanto é 15²?",
    "A": "225",
    "B": "210",
    "C": "240",
    "D": "235",
    "resposta": "A"
  },
  {
    "subsistema": "I Ciclo",
    "fase": "F",
    "tema": "Raiz quadrada",
    "pergunta": "Qual é a raiz quadrada de 361?",
    "A": "19",
    "B": "18",
    "C": "17",
    "D": "20",
    "resposta": "A"
  },
  {
    "subsistema": "I Ciclo",
    "fase": "I",
    "tema": "Expressões numéricas",
    "pergunta": "Resolva: 4 + (3 × 2) - 1",
    "A": "9",
    "B": "10",
    "C": "7",
    "D": "8",
    "resposta": "D"
  },
  {
    "subsistema": "I Ciclo",
    "fase": "I",
    "tema": "Frações",
    "pergunta": "Qual é a fração equivalente a 2/4?",
    "A": "1/2",
    "B": "3/4",
    "C": "2/2",
    "D": "1/4",
    "resposta": "A"
  },
  {
    "subsistema": "I Ciclo",
    "fase": "I",
    "tema": "MMC",
    "pergunta": "Qual é o MMC entre 6 e 8?",
    "A": "24",
    "B": "12",
    "C": "18",
    "D": "16",
    "resposta": "A"
  },
  {
    "subsistema": "I Ciclo",
    "fase": "I",
    "tema": "Equações",
    "pergunta": "Qual é o valor de x em: x + 3 = 10?",
    "A": "7",
    "B": "8",
    "C": "6",
    "D": "9",
    "resposta": "A"
  },
  {
    "subsistema": "I Ciclo",
    "fase": "I",
    "tema": "Números negativos",
    "pergunta": "Qual é o resultado de -3 + 5?",
    "A": "2",
    "B": "-2",
    "C": "1",
    "D": "8",
    "resposta": "A"
  },
  {
    "subsistema": "I Ciclo",
    "fase": "I",
    "tema": "Raiz quadrada",
    "pergunta": "Qual é a raiz quadrada de 225?",
    "A": "15",
    "B": "14",
    "C": "12",
    "D": "16",
    "resposta": "A"
  },
  {
    "subsistema": "I Ciclo",
    "fase": "I",
    "tema": "MDC",
    "pergunta": "Qual é o MDC entre 12 e 18?",
    "A": "6",
    "B": "3",
    "C": "4",
    "D": "2",
    "resposta": "A"
  },
  {
    "subsistema": "I Ciclo",
    "fase": "I",
    "tema": "Potência",
    "pergunta": "Quanto é 2³ × 2?",
    "A": "16",
    "B": "10",
    "C": "14",
    "D": "8",
    "resposta": "A"
  },
  {
    "subsistema": "I Ciclo",
    "fase": "I",
    "tema": "Expressões numéricas",
    "pergunta": "Resolva: (5 + 2) × 3 - 1",
    "A": "20",
    "B": "19",
    "C": "18",
    "D": "21",
    "resposta": "B"
  },
  {
    "subsistema": "I Ciclo",
    "fase": "I",
    "tema": "Equações",
    "pergunta": "Se x - 4 = 9, quanto vale x?",
    "A": "13",
    "B": "12",
    "C": "14",
    "D": "15",
    "resposta": "A"
  },
  {
    "subsistema": "I Ciclo",
    "fase": "I",
    "tema": "Expressões numéricas",
    "pergunta": "Resolva: (6 × 3) + 4 - 2",
    "A": "20",
    "B": "22",
    "C": "18",
    "D": "19",
    "resposta": "A"
  },
  {
    "subsistema": "I Ciclo",
    "fase": "I",
    "tema": "Frações",
    "pergunta": "Qual é a soma de 1/4 + 1/8?",
    "A": "3/8",
    "B": "2/4",
    "C": "5/8",
    "D": "1/2",
    "resposta": "C"
  },
  {
    "subsistema": "I Ciclo",
    "fase": "I",
    "tema": "MMC",
    "pergunta": "MMC de 4 e 6 é:",
    "A": "12",
    "B": "10",
    "C": "24",
    "D": "18",
    "resposta": "A"
  },
  {
    "subsistema": "I Ciclo",
    "fase": "I",
    "tema": "Equações",
    "pergunta": "Resolva: 3x = 12. Qual o valor de x?",
    "A": "4",
    "B": "3",
    "C": "5",
    "D": "6",
    "resposta": "A"
  },
  {
    "subsistema": "I Ciclo",
    "fase": "I",
    "tema": "Números negativos",
    "pergunta": "Qual é o valor de -5 + (-3)?",
    "A": "-8",
    "B": "-2",
    "C": "2",
    "D": "8",
    "resposta": "A"
  },
  {
    "subsistema": "I Ciclo",
    "fase": "I",
    "tema": "Raiz quadrada",
    "pergunta": "A raiz quadrada de 169 é:",
    "A": "13",
    "B": "14",
    "C": "12",
    "D": "15",
    "resposta": "A"
  },
  {
    "subsistema": "I Ciclo",
    "fase": "I",
    "tema": "MDC",
    "pergunta": "MDC entre 16 e 24 é:",
    "A": "8",
    "B": "4",
    "C": "6",
    "D": "2",
    "resposta": "A"
  },
  {
    "subsistema": "I Ciclo",
    "fase": "I",
    "tema": "Potência",
    "pergunta": "Resolva: 3² + 2²",
    "A": "13",
    "B": "12",
    "C": "14",
    "D": "11",
    "resposta": "A"
  },
  {
    "subsistema": "I Ciclo",
    "fase": "I",
    "tema": "Expressões numéricas",
    "pergunta": "Resolva: (2 × 4) + (6 ÷ 2)",
    "A": "11",
    "B": "12",
    "C": "10",
    "D": "9",
    "resposta": "A"
  },
  {
    "subsistema": "I Ciclo",
    "fase": "I",
    "tema": "Equações",
    "pergunta": "Se x/2 = 5, qual é o valor de x?",
    "A": "10",
    "B": "8",
    "C": "12",
    "D": "5",
    "resposta": "A"
  },
  {
    "subsistema": "I Ciclo",
    "fase": "I",
    "tema": "Expressões numéricas",
    "pergunta": "Resolva: (7 × 2) + (10 ÷ 2)",
    "A": "19",
    "B": "18",
    "C": "17",
    "D": "20",
    "resposta": "A"
  },
  {
    "subsistema": "I Ciclo",
    "fase": "I",
    "tema": "Frações",
    "pergunta": "Quanto é 3/5 + 1/5?",
    "A": "4/5",
    "B": "2/5",
    "C": "1/2",
    "D": "5/5",
    "resposta": "A"
  },
  {
    "subsistema": "I Ciclo",
    "fase": "I",
    "tema": "MMC",
    "pergunta": "MMC entre 9 e 12 é:",
    "A": "36",
    "B": "18",
    "C": "27",
    "D": "45",
    "resposta": "A"
  },
  {
    "subsistema": "I Ciclo",
    "fase": "I",
    "tema": "Equações",
    "pergunta": "Resolva: 2x + 3 = 11",
    "A": "4",
    "B": "5",
    "C": "3",
    "D": "6",
    "resposta": "A"
  },
  {
    "subsistema": "I Ciclo",
    "fase": "I",
    "tema": "Números negativos",
    "pergunta": "Qual o resultado de -2 - 6?",
    "A": "-8",
    "B": "-4",
    "C": "-6",
    "D": "-10",
    "resposta": "A"
  },
  {
    "subsistema": "I Ciclo",
    "fase": "I",
    "tema": "Raiz quadrada",
    "pergunta": "A raiz quadrada de 196 é:",
    "A": "14",
    "B": "13",
    "C": "12",
    "D": "15",
    "resposta": "A"
  },
  {
    "subsistema": "I Ciclo",
    "fase": "I",
    "tema": "MDC",
    "pergunta": "MDC entre 30 e 45 é:",
    "A": "15",
    "B": "10",
    "C": "5",
    "D": "6",
    "resposta": "A"
  },
  {
    "subsistema": "I Ciclo",
    "fase": "I",
    "tema": "Potência",
    "pergunta": "Quanto é 5² + 4²?",
    "A": "41",
    "B": "40",
    "C": "39",
    "D": "42",
    "resposta": "A"
  },
  {
    "subsistema": "I Ciclo",
    "fase": "I",
    "tema": "Expressões numéricas",
    "pergunta": "Resolva: 10 + (6 ÷ 3) × 4",
    "A": "18",
    "B": "16",
    "C": "20",
    "D": "22",
    "resposta": "A"
  },
  {
    "subsistema": "I Ciclo",
    "fase": "I",
    "tema": "Equações",
    "pergunta": "Se x - 2 = 7, então x é igual a:",
    "A": "9",
    "B": "10",
    "C": "8",
    "D": "7",
    "resposta": "A"
  },
  {
    "subsistema": "I Ciclo",
    "fase": "I",
    "tema": "Expressões numéricas",
    "pergunta": "Resolva: (5 × 3) - (4 ÷ 2)",
    "A": "13",
    "B": "15",
    "C": "14",
    "D": "11",
    "resposta": "A"
  },
  {
    "subsistema": "I Ciclo",
    "fase": "I",
    "tema": "Frações",
    "pergunta": "Some: 2/3 + 1/6",
    "A": "5/6",
    "B": "3/6",
    "C": "2/6",
    "D": "1/2",
    "resposta": "A"
  },
  {
    "subsistema": "I Ciclo",
    "fase": "I",
    "tema": "MMC",
    "pergunta": "MMC entre 5 e 7 é:",
    "A": "35",
    "B": "30",
    "C": "25",
    "D": "40",
    "resposta": "A"
  },
  {
    "subsistema": "I Ciclo",
    "fase": "I",
    "tema": "Equações",
    "pergunta": "Resolva: 5x = 30. Qual é o valor de x?",
    "A": "6",
    "B": "5",
    "C": "7",
    "D": "8",
    "resposta": "A"
  },
  {
    "subsistema": "I Ciclo",
    "fase": "I",
    "tema": "Números negativos",
    "pergunta": "Quanto é -4 - 5?",
    "A": "-9",
    "B": "-1",
    "C": "-5",
    "D": "-7",
    "resposta": "A"
  },
  {
    "subsistema": "I Ciclo",
    "fase": "I",
    "tema": "Raiz quadrada",
    "pergunta": "A raiz quadrada de 121 é:",
    "A": "11",
    "B": "10",
    "C": "12",
    "D": "13",
    "resposta": "A"
  },
  {
    "subsistema": "I Ciclo",
    "fase": "I",
    "tema": "MDC",
    "pergunta": "MDC entre 36 e 48 é:",
    "A": "12",
    "B": "6",
    "C": "8",
    "D": "4",
    "resposta": "A"
  },
  {
    "subsistema": "I Ciclo",
    "fase": "I",
    "tema": "Potência",
    "pergunta": "Quanto é 6² - 2²?",
    "A": "32",
    "B": "30",
    "C": "28",
    "D": "34",
    "resposta": "A"
  },
  {
    "subsistema": "I Ciclo",
    "fase": "I",
    "tema": "Expressões numéricas",
    "pergunta": "Resolva: (3 × 5) + (12 ÷ 3)",
    "A": "21",
    "B": "19",
    "C": "20",
    "D": "22",
    "resposta": "A"
  },
  {
    "subsistema": "I Ciclo",
    "fase": "I",
    "tema": "Equações",
    "pergunta": "Se 2x + 2 = 10, então x é:",
    "A": "4",
    "B": "3",
    "C": "5",
    "D": "6",
    "resposta": "A"
  },
  {
    "subsistema": "I Ciclo",
    "fase": "I",
    "tema": "Expressões numéricas",
    "pergunta": "Resolva: 4 × (3 + 2) - 6",
    "A": "14",
    "B": "16",
    "C": "12",
    "D": "18",
    "resposta": "A"
  },
  {
    "subsistema": "I Ciclo",
    "fase": "I",
    "tema": "Frações",
    "pergunta": "Some: 1/5 + 2/5 + 1/5",
    "A": "4/5",
    "B": "3/5",
    "C": "5/5",
    "D": "2/5",
    "resposta": "A"
  },
  {
    "subsistema": "I Ciclo",
    "fase": "I",
    "tema": "MMC",
    "pergunta": "MMC entre 10 e 12 é:",
    "A": "60",
    "B": "30",
    "C": "40",
    "D": "20",
    "resposta": "A"
  },
  {
    "subsistema": "I Ciclo",
    "fase": "I",
    "tema": "Equações",
    "pergunta": "Resolva: x + x + 4 = 12",
    "A": "4",
    "B": "5",
    "C": "3",
    "D": "6",
    "resposta": "A"
  },
  {
    "subsistema": "I Ciclo",
    "fase": "I",
    "tema": "Números negativos",
    "pergunta": "Quanto é -10 + 3?",
    "A": "-7",
    "B": "-13",
    "C": "7",
    "D": "13",
    "resposta": "A"
  },
  {
    "subsistema": "I Ciclo",
    "fase": "I",
    "tema": "Raiz quadrada",
    "pergunta": "Raiz quadrada de 256 é:",
    "A": "16",
    "B": "15",
    "C": "14",
    "D": "17",
    "resposta": "A"
  },
  {
    "subsistema": "I Ciclo",
    "fase": "I",
    "tema": "MDC",
    "pergunta": "MDC entre 42 e 56 é:",
    "A": "14",
    "B": "12",
    "C": "10",
    "D": "8",
    "resposta": "A"
  },
  {
    "subsistema": "I Ciclo",
    "fase": "I",
    "tema": "Potência",
    "pergunta": "Quanto é 7² - 3²?",
    "A": "40",
    "B": "36",
    "C": "45",
    "D": "49",
    "resposta": "A"
  },
  {
    "subsistema": "I Ciclo",
    "fase": "I",
    "tema": "Expressões numéricas",
    "pergunta": "Resolva: (8 ÷ 2) + (3 × 3)",
    "A": "13",
    "B": "14",
    "C": "12",
    "D": "15",
    "resposta": "A"
  },
  {
    "subsistema": "I Ciclo",
    "fase": "I",
    "tema": "Equações",
    "pergunta": "Se 3x - 3 = 12, quanto vale x?",
    "A": "5",
    "B": "6",
    "C": "4",
    "D": "3",
    "resposta": "A"
  },
  {
    "subsistema": "I Ciclo",
    "fase": "D",
    "tema": "Problemas com frações",
    "pergunta": "Joana comeu 1/3 de um bolo e Maria comeu 1/4. Qual a fração total do bolo que foi comida?",
    "A": "7/12",
    "B": "2/7",
    "C": "5/7",
    "D": "2/3",
    "resposta": "A"
  },
  {
    "subsistema": "I Ciclo",
    "fase": "D",
    "tema": "Problemas com expressões",
    "pergunta": "Se um lápis custa 25 Kz e um caderno custa o dobro, quanto custa 3 lápis e 2 cadernos?",
    "A": "175 Kz",
    "B": "150 Kz",
    "C": "160 Kz",
    "D": "140 Kz",
    "resposta": "A"
  },
  {
    "subsistema": "I Ciclo",
    "fase": "D",
    "tema": "Problemas com porcentagem",
    "pergunta": "Se uma escola tem 200 alunos e 25% são meninas, quantas meninas há?",
    "A": "50",
    "B": "75",
    "C": "60",
    "D": "40",
    "resposta": "A"
  },
  {
    "subsistema": "I Ciclo",
    "fase": "D",
    "tema": "Problemas com unidades de medida",
    "pergunta": "Pedro comprou 1,5 kg de arroz e mais 2,75 kg de batata. Qual o peso total?",
    "A": "4,25 kg",
    "B": "3,5 kg",
    "C": "4 kg",
    "D": "5 kg",
    "resposta": "A"
  },
  {
    "subsistema": "I Ciclo",
    "fase": "D",
    "tema": "Problemas com tempo",
    "pergunta": "Se uma aula começa às 7h30 e dura 1h45min, que horas termina?",
    "A": "9h15",
    "B": "9h00",
    "C": "8h45",
    "D": "10h00",
    "resposta": "A"
  },
  {
    "subsistema": "I Ciclo",
    "fase": "D",
    "tema": "Problemas com equações",
    "pergunta": "João tem o dobro da idade de Pedro. Se juntos têm 18 anos, qual é a idade de Pedro?",
    "A": "6 anos",
    "B": "9 anos",
    "C": "12 anos",
    "D": "8 anos",
    "resposta": "A"
  },
  {
    "subsistema": "I Ciclo",
    "fase": "D",
    "tema": "Problemas com MDC e MMC",
    "pergunta": "Duas luzes piscam a cada 6 e 8 segundos. Em quanto tempo as duas piscarão juntas novamente?",
    "A": "24 segundos",
    "B": "48 segundos",
    "C": "18 segundos",
    "D": "12 segundos",
    "resposta": "A"
  },
  {
    "subsistema": "I Ciclo",
    "fase": "D",
    "tema": "Problemas com multiplicação",
    "pergunta": "Um caderno custa 120 Kz. Quantos cadernos posso comprar com 1.200 Kz?",
    "A": "10",
    "B": "12",
    "C": "11",
    "D": "8",
    "resposta": "A"
  },
  {
    "subsistema": "I Ciclo",
    "fase": "D",
    "tema": "Problemas com divisão",
    "pergunta": "Uma professora dividiu 48 livros igualmente entre 6 alunos. Quantos livros cada aluno recebeu?",
    "A": "8",
    "B": "6",
    "C": "7",
    "D": "9",
    "resposta": "A"
  },
  {
    "subsistema": "I Ciclo",
    "fase": "D",
    "tema": "Problemas com gráficos (interpretação)",
    "pergunta": "Num gráfico de barras, uma barra mostra 40 alunos em Matemática e outra 30 em Língua Portuguesa. Quantos alunos a mais têm em Matemática?",
    "A": "10",
    "B": "15",
    "C": "20",
    "D": "5",
    "resposta": "A"
  },
  {
    "subsistema": "I Ciclo",
    "fase": "D",
    "tema": "Problemas com dinheiro",
    "pergunta": "Ana comprou 2 cadernos de 350 Kz cada e uma caneta de 200 Kz. Quanto ela gastou no total?",
    "A": "900 Kz",
    "B": "1.000 Kz",
    "C": "800 Kz",
    "D": "700 Kz",
    "resposta": "A"
  },
  {
    "subsistema": "I Ciclo",
    "fase": "D",
    "tema": "Problemas com porcentagem",
    "pergunta": "Um telemóvel custa 10.000 Kz. Se houver 10% de desconto, quanto pagarei?",
    "A": "9.000 Kz",
    "B": "10.000 Kz",
    "C": "8.000 Kz",
    "D": "9.500 Kz",
    "resposta": "A"
  },
  {
    "subsistema": "I Ciclo",
    "fase": "D",
    "tema": "Problemas com proporção",
    "pergunta": "Se 3 lápis custam 90 Kz, quanto custam 5 lápis?",
    "A": "150 Kz",
    "B": "120 Kz",
    "C": "100 Kz",
    "D": "140 Kz",
    "resposta": "A"
  },
  {
    "subsistema": "I Ciclo",
    "fase": "D",
    "tema": "Problemas com tempo",
    "pergunta": "Um filme começou às 15h20 e durou 1h50min. A que horas terminou?",
    "A": "17h10",
    "B": "17h00",
    "C": "16h50",
    "D": "17h20",
    "resposta": "A"
  },
  {
    "subsistema": "I Ciclo",
    "fase": "D",
    "tema": "Problemas com multiplicação",
    "pergunta": "Uma caixa tem 6 pacotes e cada pacote tem 8 lápis. Quantos lápis há no total?",
    "A": "48",
    "B": "40",
    "C": "42",
    "D": "50",
    "resposta": "A"
  },
  {
    "subsistema": "I Ciclo",
    "fase": "D",
    "tema": "Problemas com divisão",
    "pergunta": "Um professor tem 120 folhas para dividir igualmente entre 10 alunos. Quantas folhas cada um recebe?",
    "A": "12",
    "B": "11",
    "C": "13",
    "D": "14",
    "resposta": "A"
  },
  {
    "subsistema": "I Ciclo",
    "fase": "D",
    "tema": "Problemas com gráficos",
    "pergunta": "Num gráfico de colunas, a barra de Matemática mostra 50 alunos, e a de Ciências 40. Quantos alunos no total?",
    "A": "90",
    "B": "80",
    "C": "100",
    "D": "85",
    "resposta": "A"
  },
  {
    "subsistema": "I Ciclo",
    "fase": "D",
    "tema": "Problemas com equações",
    "pergunta": "Se x + x + 2 = 10, qual o valor de x?",
    "A": "4",
    "B": "3",
    "C": "2",
    "D": "5",
    "resposta": "A"
  },
  {
    "subsistema": "I Ciclo",
    "fase": "D",
    "tema": "Problemas com área",
    "pergunta": "Qual é a área de um retângulo de 6m por 4m?",
    "A": "24 m²",
    "B": "20 m²",
    "C": "26 m²",
    "D": "30 m²",
    "resposta": "A"
  },
  {
    "subsistema": "I Ciclo",
    "fase": "D",
    "tema": "Problemas com volume",
    "pergunta": "Um recipiente tem 3 litros. Quantos ml isso representa?",
    "A": "3000 ml",
    "B": "1500 ml",
    "C": "1000 ml",
    "D": "2000 ml",
    "resposta": "A"
  },
  {
    "subsistema": "I Ciclo",
    "fase": "D",
    "tema": "Problemas com adição de números grandes",
    "pergunta": "Um aluno leu 324 páginas em janeiro e 486 em fevereiro. Quantas páginas ele leu no total?",
    "A": "810",
    "B": "800",
    "C": "820",
    "D": "790",
    "resposta": "A"
  },
  {
    "subsistema": "I Ciclo",
    "fase": "D",
    "tema": "Problemas com subtração no cotidiano",
    "pergunta": "Uma loja tinha 120 produtos. Vendeu 85. Quantos produtos restaram?",
    "A": "35",
    "B": "45",
    "C": "25",
    "D": "30",
    "resposta": "A"
  },
  {
    "subsistema": "I Ciclo",
    "fase": "D",
    "tema": "Problemas com horas e minutos",
    "pergunta": "Se um filme começa às 14h45 e termina às 17h10, quanto tempo ele durou?",
    "A": "2h25min",
    "B": "2h15min",
    "C": "2h30min",
    "D": "2h20min",
    "resposta": "A"
  },
  {
    "subsistema": "I Ciclo",
    "fase": "D",
    "tema": "Problemas com frações de quantidades",
    "pergunta": "Carlos tem 60 balões. Se ele dá 2/5 aos colegas, quantos balões ele dá?",
    "A": "24",
    "B": "20",
    "C": "30",
    "D": "25",
    "resposta": "A"
  },
  {
    "subsistema": "I Ciclo",
    "fase": "D",
    "tema": "Problemas com distância",
    "pergunta": "Maria caminhou 2,3 km de manhã e 3,7 km à tarde. Qual foi a distância total percorrida?",
    "A": "6 km",
    "B": "5,9 km",
    "C": "6,1 km",
    "D": "5,8 km",
    "resposta": "A"
  },
  {
    "subsistema": "I Ciclo",
    "fase": "D",
    "tema": "Problemas com medidas de capacidade",
    "pergunta": "Um garrafão contém 5 litros de água. Quantos copos de 250 ml ele pode encher?",
    "A": "20",
    "B": "25",
    "C": "15",
    "D": "30",
    "resposta": "A"
  },
  {
    "subsistema": "I Ciclo",
    "fase": "D",
    "tema": "Problemas com salário",
    "pergunta": "Se uma pessoa ganha 15.000 Kz por mês, quanto ela recebe em 6 meses?",
    "A": "90.000 Kz",
    "B": "85.000 Kz",
    "C": "80.000 Kz",
    "D": "95.000 Kz",
    "resposta": "A"
  },
  {
    "subsistema": "I Ciclo",
    "fase": "D",
    "tema": "Problemas com desconto",
    "pergunta": "Um livro custa 2.000 Kz e está com 25% de desconto. Qual o preço com desconto?",
    "A": "1.500 Kz",
    "B": "1.600 Kz",
    "C": "1.400 Kz",
    "D": "1.300 Kz",
    "resposta": "A"
  },
  {
    "subsistema": "I Ciclo",
    "fase": "D",
    "tema": "Problemas com multiplicação e adição",
    "pergunta": "Uma mochila custa 1.800 Kz e um estojo custa 700 Kz. Qual o custo total de 2 mochilas e 3 estojos?",
    "A": "5.700 Kz",
    "B": "5.600 Kz",
    "C": "5.800 Kz",
    "D": "5.500 Kz",
    "resposta": "A"
  },
  {
    "subsistema": "I Ciclo",
    "fase": "D",
    "tema": "Problemas com leitura de tabela",
    "pergunta": "Se em uma tabela consta que João tem 3 bolas, Ana tem 5 e Pedro tem 4, quantas bolas há no total?",
    "A": "12",
    "B": "13",
    "C": "14",
    "D": "15",
    "resposta": "A"
  },
  {
    "subsistema": "I Ciclo",
    "fase": "D",
    "tema": "Problemas com compras",
    "pergunta": "Comprei um caderno por 700 Kz e um lápis por 300 Kz. Paguei com uma nota de 2.000 Kz. Quanto recebi de troco?",
    "A": "1.000 Kz",
    "B": "1.100 Kz",
    "C": "900 Kz",
    "D": "800 Kz",
    "resposta": "A"
  },
  {
    "subsistema": "I Ciclo",
    "fase": "D",
    "tema": "Problemas com frações equivalentes",
    "pergunta": "Qual fração é equivalente a 2/3?",
    "A": "4/6",
    "B": "3/5",
    "C": "5/8",
    "D": "2/5",
    "resposta": "A"
  },
  {
    "subsistema": "I Ciclo",
    "fase": "D",
    "tema": "Problemas com média aritmética",
    "pergunta": "As notas de Pedro foram: 14, 16 e 18. Qual a média?",
    "A": "16",
    "B": "17",
    "C": "15",
    "D": "18",
    "resposta": "A"
  },
  {
    "subsistema": "I Ciclo",
    "fase": "D",
    "tema": "Problemas com tabela de preços",
    "pergunta": "Se cada maçã custa 150 Kz, quanto pago por 6 maçãs?",
    "A": "900 Kz",
    "B": "800 Kz",
    "C": "850 Kz",
    "D": "950 Kz",
    "resposta": "A"
  },
  {
    "subsistema": "I Ciclo",
    "fase": "D",
    "tema": "Problemas com área de figuras planas",
    "pergunta": "Um quadrado tem lado de 5 cm. Qual é sua área?",
    "A": "25 cm²",
    "B": "20 cm²",
    "C": "30 cm²",
    "D": "15 cm²",
    "resposta": "A"
  },
  {
    "subsistema": "I Ciclo",
    "fase": "D",
    "tema": "Problemas com perímetro",
    "pergunta": "Qual o perímetro de um triângulo com lados de 6 cm, 8 cm e 10 cm?",
    "A": "24 cm",
    "B": "20 cm",
    "C": "26 cm",
    "D": "22 cm",
    "resposta": "A"
  },
  {
    "subsistema": "I Ciclo",
    "fase": "D",
    "tema": "Problemas com tempo e distância",
    "pergunta": "Se um carro anda a 60 km/h, quanto percorre em 3 horas?",
    "A": "180 km",
    "B": "150 km",
    "C": "200 km",
    "D": "160 km",
    "resposta": "A"
  },
  {
    "subsistema": "I Ciclo",
    "fase": "D",
    "tema": "Problemas com leitura de gráfico",
    "pergunta": "Num gráfico de colunas, João tem 15 livros, Ana tem 20 e Pedro 10. Quantos livros há no total?",
    "A": "45",
    "B": "40",
    "C": "50",
    "D": "35",
    "resposta": "A"
  },
  {
    "subsistema": "I Ciclo",
    "fase": "D",
    "tema": "Problemas com múltiplos",
    "pergunta": "Qual é o menor múltiplo comum de 6 e 9?",
    "A": "18",
    "B": "12",
    "C": "24",
    "D": "15",
    "resposta": "A"
  },
  {
    "subsistema": "I Ciclo",
    "fase": "D",
    "tema": "Problemas com figuras geométricas",
    "pergunta": "Quantos lados tem um hexágono?",
    "A": "6",
    "B": "5",
    "C": "7",
    "D": "8",
    "resposta": "A"
  }
];